### Introduction
* Fast Mathematical Computational Library
* General purpose library available in Python is slow
* Specialized for doing mathematical computation
* Internally implemented using C - so fast
* High dimensional Computation
* Inbuilt utilities
* Mutabale

#### NumPy Creation
* Create from list
* Create zeros
* Create ones
* Fill
* range
* random

In [2]:
import numpy as np

In [5]:
l = [1,2,3,4,5]
n1 = np.array(l)

In [6]:
n2 = np.zeros(10,dtype=np.int)

In [7]:
n3 = np.ones(10,dtype=np.float)

In [9]:
n4 = np.full(10,111)

In [10]:
n4

array([111, 111, 111, 111, 111, 111, 111, 111, 111, 111])

In [11]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [15]:
d = np.ones((3,3,3))

In [19]:
d[1][1][1]

1.0

In [20]:
n1

array([1, 2, 3, 4, 5])

In [21]:
n1[0]

1

In [22]:
n1[-1]

5

In [23]:
n1[4]

5

In [26]:
np.random.rand(10)

array([ 0.67149444,  0.4677635 ,  0.17438498,  0.00247025,  0.83753791,
        0.58560594,  0.26906071,  0.42705933,  0.9750533 ,  0.02834121])

In [27]:
np.random.randint(0,10,size=(3,3))

array([[8, 5, 9],
       [2, 3, 5],
       [5, 1, 6]])

In [28]:
np.random.randint(2,20,size=100)

array([12, 15,  9, 15,  7, 10,  5,  9, 17,  9,  8, 12,  5, 11,  9, 11, 11,
        5,  9, 14, 12,  8,  2,  6,  4, 14,  3,  7,  3, 16,  7,  5, 14, 15,
       14,  9,  6, 13,  6,  4,  8, 11,  9, 19, 17,  3, 11,  2, 16,  7, 18,
        3, 17,  4, 12,  7, 14, 10, 11,  5, 14, 14, 14,  7,  8,  2, 17,  3,
       11,  9, 13,  3, 12, 15, 11, 14, 18, 17,  7, 19, 19, 19, 13,  5, 15,
        4,  6,  3,  7, 18, 11,  9, 12, 10, 19,  3, 15, 14, 19,  6])

### Accessing elements

In [29]:
data = np.random.randint(2,20,size=(5,5))

In [30]:
data

array([[ 5,  7,  7,  7,  2],
       [19, 15, 15, 12, 19],
       [17, 13, 17, 12,  9],
       [16,  4, 11,  2, 11],
       [10, 14,  4,  7, 19]])

In [31]:
data[0]

array([5, 7, 7, 7, 2])

In [32]:
data[0][0]

5

In [33]:
data[:2]

array([[ 5,  7,  7,  7,  2],
       [19, 15, 15, 12, 19]])

In [34]:
data[2:]

array([[17, 13, 17, 12,  9],
       [16,  4, 11,  2, 11],
       [10, 14,  4,  7, 19]])

In [35]:
data[:,1]

array([ 7, 15, 13,  4, 14])

In [38]:
data[:,1:4]

array([[ 7,  7,  7],
       [15, 15, 12],
       [13, 17, 12],
       [ 4, 11,  2],
       [14,  4,  7]])

In [39]:
data[:,:]

array([[ 5,  7,  7,  7,  2],
       [19, 15, 15, 12, 19],
       [17, 13, 17, 12,  9],
       [16,  4, 11,  2, 11],
       [10, 14,  4,  7, 19]])

In [40]:
data[2:4, 1:3]

array([[13, 17],
       [ 4, 11]])

In [45]:
data = np.random.randint(2,20,size=(3,3,3))

In [46]:
data

array([[[17, 15, 17],
        [15,  5,  3],
        [ 3,  4,  9]],

       [[ 2,  2,  9],
        [14,  8,  3],
        [ 4,  4,  8]],

       [[ 5,  8, 19],
        [ 8, 13, 12],
        [14, 13,  4]]])

In [51]:
data[0,:,:]

array([[17, 15, 17],
       [15,  5,  3],
       [ 3,  4,  9]])

In [54]:
data[0][0] = [99,11,11]

In [55]:
data

array([[[99, 11, 11],
        [15,  5,  3],
        [ 3,  4,  9]],

       [[ 2,  2,  9],
        [14,  8,  3],
        [ 4,  4,  8]],

       [[ 5,  8, 19],
        [ 8, 13, 12],
        [14, 13,  4]]])

### Shape, Size & Dimension

In [56]:
data.shape

(3, 3, 3)

In [57]:
data.ndim

3

In [58]:
data.size

27

In [59]:
data = np.random.randint(2,20,size=(8,8))

In [60]:
data

array([[18, 11,  3, 13, 14,  2, 12, 16],
       [19,  4,  7,  2, 11,  2, 12, 10],
       [10,  5, 17, 17, 13,  9,  3, 17],
       [13,  5, 14,  4,  3,  4, 16,  8],
       [ 4, 16, 19, 14,  9, 11, 17, 14],
       [ 2,  8,  9, 18,  7, 17, 18, 10],
       [ 6, 17, 17,  2,  5, 18,  4,  7],
       [ 2, 19,  8, 12, 17,  9, 19, 19]])

In [63]:
data.reshape((2,2,2,4,2)).shape?

Object `shape` not found.


In [64]:
data.reshape((2,2,2,4,2)).shape

(2, 2, 2, 4, 2)

In [65]:
d = np.random.randint(1,100,size=10)

In [66]:
d

array([58, 19, 50, 61, 27, 62, 48, 50, 62, 18])

In [67]:
e = d.reshape((10,1))

In [69]:
e

array([[58],
       [19],
       [50],
       [61],
       [27],
       [62],
       [48],
       [50],
       [62],
       [18]])

In [70]:
f = d.reshape((1,10))

In [72]:
f.ndim

2

In [76]:
d[:,np.newaxis,np.newaxis]

array([[[58]],

       [[19]],

       [[50]],

       [[61]],

       [[27]],

       [[62]],

       [[48]],

       [[50]],

       [[62]],

       [[18]]])

In [75]:
d

array([58, 19, 50, 61, 27, 62, 48, 50, 62, 18])

In [77]:
data = np.random.randint(2,20,size=(8,8))

In [80]:
data.reshape((8,1,8))

array([[[15,  5, 13, 16, 13, 15, 15, 15]],

       [[ 3, 15, 11,  8, 18, 14, 15, 13]],

       [[18, 16,  6,  9, 15,  9, 12,  3]],

       [[ 5, 15,  2, 19, 19,  9,  2,  5]],

       [[ 2, 13,  3, 17, 13,  2,  7, 14]],

       [[12,  9, 16,  6,  7,  6,  3, 13]],

       [[ 4, 12, 11,  5,  4, 13, 14, 16]],

       [[ 6,  7,  8, 13, 15,  8,  2,  2]]])

In [81]:
data.reshape((8,8,1))

array([[[15],
        [ 5],
        [13],
        [16],
        [13],
        [15],
        [15],
        [15]],

       [[ 3],
        [15],
        [11],
        [ 8],
        [18],
        [14],
        [15],
        [13]],

       [[18],
        [16],
        [ 6],
        [ 9],
        [15],
        [ 9],
        [12],
        [ 3]],

       [[ 5],
        [15],
        [ 2],
        [19],
        [19],
        [ 9],
        [ 2],
        [ 5]],

       [[ 2],
        [13],
        [ 3],
        [17],
        [13],
        [ 2],
        [ 7],
        [14]],

       [[12],
        [ 9],
        [16],
        [ 6],
        [ 7],
        [ 6],
        [ 3],
        [13]],

       [[ 4],
        [12],
        [11],
        [ 5],
        [ 4],
        [13],
        [14],
        [16]],

       [[ 6],
        [ 7],
        [ 8],
        [13],
        [15],
        [ 8],
        [ 2],
        [ 2]]])

In [82]:
data.reshape((1,8,8))

array([[[15,  5, 13, 16, 13, 15, 15, 15],
        [ 3, 15, 11,  8, 18, 14, 15, 13],
        [18, 16,  6,  9, 15,  9, 12,  3],
        [ 5, 15,  2, 19, 19,  9,  2,  5],
        [ 2, 13,  3, 17, 13,  2,  7, 14],
        [12,  9, 16,  6,  7,  6,  3, 13],
        [ 4, 12, 11,  5,  4, 13, 14, 16],
        [ 6,  7,  8, 13, 15,  8,  2,  2]]])