In [1]:
import numpy as np

### Introduction
* Lot of mathematical calculation really fast
* Homogenous data structure - Stores data of same type

### Creation
* From list
* With all zeros
* With all ones
* With random values

In [2]:
a = np.array([1,2,3.3,9,8])

In [3]:
a

array([ 1. ,  2. ,  3.3,  9. ,  8. ])

In [5]:

a.dtype

dtype('float64')

In [6]:
a = np.array([1,2,3,9,8])

In [7]:
a.dtype

dtype('int32')

In [11]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((4,4,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [14]:
np.ones((5,5,5))

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [18]:
#Generate 100 equally spaced numbers from 0 tp 10
res = np.linspace(start=0.0, stop=10.0, num=100)

In [19]:
np.round(res,2)

array([  0.  ,   0.1 ,   0.2 ,   0.3 ,   0.4 ,   0.51,   0.61,   0.71,
         0.81,   0.91,   1.01,   1.11,   1.21,   1.31,   1.41,   1.52,
         1.62,   1.72,   1.82,   1.92,   2.02,   2.12,   2.22,   2.32,
         2.42,   2.53,   2.63,   2.73,   2.83,   2.93,   3.03,   3.13,
         3.23,   3.33,   3.43,   3.54,   3.64,   3.74,   3.84,   3.94,
         4.04,   4.14,   4.24,   4.34,   4.44,   4.55,   4.65,   4.75,
         4.85,   4.95,   5.05,   5.15,   5.25,   5.35,   5.45,   5.56,
         5.66,   5.76,   5.86,   5.96,   6.06,   6.16,   6.26,   6.36,
         6.46,   6.57,   6.67,   6.77,   6.87,   6.97,   7.07,   7.17,
         7.27,   7.37,   7.47,   7.58,   7.68,   7.78,   7.88,   7.98,
         8.08,   8.18,   8.28,   8.38,   8.48,   8.59,   8.69,   8.79,
         8.89,   8.99,   9.09,   9.19,   9.29,   9.39,   9.49,   9.6 ,
         9.7 ,   9.8 ,   9.9 ,  10.  ])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.rand(100)

array([ 0.9960088 ,  0.76537058,  0.6831499 ,  0.73654067,  0.56727719,
        0.74968866,  0.78255322,  0.23691665,  0.56588098,  0.26009985,
        0.20742233,  0.17849461,  0.07663208,  0.680924  ,  0.45995515,
        0.43373717,  0.50738798,  0.11523627,  0.8411345 ,  0.40966278,
        0.31453491,  0.64469697,  0.26918366,  0.8855568 ,  0.74379813,
        0.66125093,  0.56063408,  0.24259507,  0.3826801 ,  0.11800361,
        0.79602902,  0.95377719,  0.25858757,  0.1855338 ,  0.30741121,
        0.32379092,  0.72498783,  0.4910789 ,  0.26438945,  0.47615152,
        0.58369739,  0.67668982,  0.32538146,  0.31463738,  0.05087638,
        0.35886069,  0.46834971,  0.70341364,  0.54039576,  0.06167018,
        0.21185512,  0.18601053,  0.82817134,  0.04346542,  0.62682518,
        0.37370381,  0.84694108,  0.71979707,  0.66617683,  0.47169074,
        0.60803568,  0.32467488,  0.808681  ,  0.71474664,  0.81090665,
        0.27646226,  0.66626806,  0.19040316,  0.63102011,  0.73

In [23]:
#Generate 4 X 4 matrix from 5 to 10 
np.random.randint(5,10,size=(4,4))

array([[5, 9, 5, 6],
       [8, 9, 9, 6],
       [7, 8, 9, 5],
       [6, 8, 6, 6]])

### Basic Operation

In [24]:
a = np.array([20,30,40,50])
b = np.array([2,3,4,5])

In [25]:
a - b

array([18, 27, 36, 45])

In [26]:
a + b

array([22, 33, 44, 55])

In [27]:
a /2 

array([ 10.,  15.,  20.,  25.])

In [28]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [29]:
A = np.array([ [1,1], [0,1]])

In [30]:
B = np.array([ [2,0], [3,4]])

In [31]:
A * B 
#elementwise product

array([[2, 0],
       [0, 4]])

In [32]:
A

array([[1, 1],
       [0, 1]])

In [33]:
B

array([[2, 0],
       [3, 4]])

In [34]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [35]:
np.matmul(A,B)

array([[5, 4],
       [3, 4]])

In [36]:
np.average(A)

0.75

In [37]:
np.median(A)

1.0

In [38]:
a = np.array([1,2,3])

In [39]:
a ** 2

array([1, 4, 9], dtype=int32)

In [40]:
min(a)

1

In [41]:
a

array([1, 2, 3])

In [42]:
a[0]

1

In [43]:
a[-1]

3

In [44]:
a[1:3]

array([2, 3])

In [45]:
a[::-1]

array([3, 2, 1])

In [48]:
def f(x,y):
    return x*y

In [49]:
np.fromfunction(f,(5,5))

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   4.],
       [  0.,   2.,   4.,   6.,   8.],
       [  0.,   3.,   6.,   9.,  12.],
       [  0.,   4.,   8.,  12.,  16.]])

In [53]:
data = np.floor(10 * np.random.random((3,4)))

In [54]:
data.shape

(3, 4)

In [55]:
data.ndim

2

In [56]:
data.size

12

In [58]:
oneddata = data.ravel()

In [59]:
data

array([[ 9.,  8.,  3.,  8.],
       [ 4.,  3.,  7.,  8.],
       [ 8.,  8.,  1.,  6.]])

In [65]:
oneddata.shape

(12,)

oneddata.reshape((4,3))

In [66]:
oneddata[:,np.newaxis].shape

(12, 1)

In [67]:
oneddata.reshape((6,2))

array([[ 9.,  8.],
       [ 3.,  8.],
       [ 4.,  3.],
       [ 7.,  8.],
       [ 8.,  8.],
       [ 1.,  6.]])

### Stacking different arrays

In [75]:
a = np.arange(10).reshape((5,2))

In [76]:
b = np.arange(20).reshape((5,4))

In [78]:
#Should have same number of rows
np.hstack([a,b])

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11],
       [ 6,  7, 12, 13, 14, 15],
       [ 8,  9, 16, 17, 18, 19]])

In [79]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [80]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [81]:
a = np.arange(10).reshape((2,5))
b = np.arange(20).reshape((4,5))

In [82]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [83]:
res = np.vstack([a,b])

### Splitting the contents

In [85]:
np.hsplit(res,[3])

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17]]), array([[ 3,  4],
        [ 8,  9],
        [ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

In [86]:
np.vsplit(res,[3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4]]), array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [87]:
### Copies & Views

In [88]:
a = np.arange(12)

In [89]:
b = a

In [90]:
b.shape = 3,4

In [91]:
a.shape

(3, 4)

In [92]:
id(a)

3019009607120

In [93]:
id(b)

3019009607120

In [94]:
c = a.view()

In [95]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a is c

False

In [98]:
a.shape = 4,3

In [100]:
c.shape

(3, 4)

In [102]:
a[0,0] = 999

In [103]:
c

array([[999,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [104]:
#Copy the actual data
d = a.copy()

In [107]:
d[0,0] = 9

In [108]:
a

array([[999,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

### Perfromance measurement

In [1]:
import numpy as np

In [9]:
d = np.random.randint(0,1000000000,size=25)

In [13]:
%timeit sum(d)

C:\Users\ZekeLabs\Anaconda3-N\lib\site-packages\ipykernel_launcher.py:257: RuntimeWarning: overflow encountered in long_scalars


29.2 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
%timeit np.sum(d)

11 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Fancy indexing & index tricks

In [15]:
r = np.arange(12) ** 2

In [16]:
r[0]

0

In [17]:
r[-1]

121

In [18]:
r[2:6]

array([ 4,  9, 16, 25], dtype=int32)

In [20]:
m = r.reshape(3,4)

In [21]:
m[0][1]

1

In [23]:
m[:,2]

array([  4,  36, 100], dtype=int32)

In [24]:
m

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [26]:
m[1:3,1:3]

array([[ 25,  36],
       [ 81, 100]], dtype=int32)

In [27]:
data = np.random.randint(0,10,size=10)

In [28]:
data

array([1, 7, 9, 6, 1, 7, 8, 6, 5, 1])

In [29]:
np.argmax(data)

2

In [30]:
np.argmin(data)

0

In [31]:
np.argsort(data)

array([0, 4, 9, 8, 3, 7, 1, 5, 6, 2], dtype=int64)

In [32]:
data = np.random.randint(0,10,size=(10,10))

In [34]:
data.argsort(axis=1)

array([[2, 4, 6, 9, 0, 1, 3, 7, 5, 8],
       [5, 6, 9, 2, 8, 1, 3, 0, 4, 7],
       [2, 3, 6, 4, 0, 5, 8, 9, 1, 7],
       [5, 1, 3, 8, 2, 6, 0, 4, 7, 9],
       [2, 0, 5, 9, 7, 1, 6, 8, 3, 4],
       [4, 0, 5, 1, 6, 7, 3, 8, 9, 2],
       [2, 7, 0, 6, 3, 1, 9, 4, 5, 8],
       [0, 5, 6, 8, 3, 1, 4, 9, 2, 7],
       [4, 6, 1, 2, 0, 5, 8, 9, 3, 7],
       [1, 6, 8, 9, 2, 0, 4, 7, 5, 3]], dtype=int64)

In [35]:
data

array([[4, 6, 0, 6, 1, 8, 2, 6, 8, 3],
       [8, 7, 5, 7, 9, 2, 4, 9, 6, 4],
       [6, 9, 1, 1, 5, 6, 1, 9, 7, 8],
       [7, 3, 6, 3, 8, 2, 6, 8, 5, 8],
       [2, 6, 1, 9, 9, 3, 7, 5, 8, 4],
       [1, 4, 9, 6, 0, 1, 4, 4, 6, 6],
       [3, 7, 1, 4, 8, 9, 3, 2, 9, 7],
       [0, 4, 9, 3, 6, 2, 2, 9, 2, 6],
       [5, 3, 4, 8, 1, 6, 2, 9, 7, 7],
       [6, 0, 4, 9, 6, 8, 0, 7, 2, 3]])

In [38]:
r = np.arange(0,100,2).reshape(5,10)

In [42]:
np.argsort(r,axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int64)

### Ordering Options
* argmax, 
* argmin, 
* argsort, 
* max, 
* min, 
* sort

### Questions
* all
* any
* where

In [47]:
d = np.random.randint(1,100,size=20)

In [48]:
d

array([18, 42,  1,  5, 94, 74, 57, 44, 25, 45, 66, 27, 83, 75, 88, 31, 95,
       13, 26, 24])

In [51]:
d[np.where(d > 5)]

array([18, 42, 94, 74, 57, 44, 25, 45, 66, 27, 83, 75, 88, 31, 95, 13, 26,
       24])

### Operations
* choose, 
* compress, 
* cumprod, 
* cumsum, 
* inner, 
* ndarray.fill, 
* imag, 
* prod, 
* put, 
* putmask, 
* real, 
* sum

In [53]:
np.choose([1,2,3,3,4,5,5,5], choices=[2,4,4,5,5,5,5,5,5,5,5,6,6,6])

array([4, 4, 5, 5, 5, 5, 5, 5])

In [54]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [58]:
np.compress([False,True],a, axis=0)

array([[3, 4]])

In [57]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])