In [17]:
import numpy as np

In [3]:
x = np.array([-2,-1,1,3])

In [4]:
abs(x)

array([2, 1, 1, 3])

In [6]:
min(x)

-2

In [7]:
np.absolute(x)

array([2, 1, 1, 3])

In [8]:
np.linspace(2,10,20)

array([  2.        ,   2.42105263,   2.84210526,   3.26315789,
         3.68421053,   4.10526316,   4.52631579,   4.94736842,
         5.36842105,   5.78947368,   6.21052632,   6.63157895,
         7.05263158,   7.47368421,   7.89473684,   8.31578947,
         8.73684211,   9.15789474,   9.57894737,  10.        ])

In [9]:
x = [1,2,4,10]

In [11]:
np.log2(x)

array([ 0.        ,  1.        ,  2.        ,  3.32192809])

In [13]:
a = np.arange(5)

In [19]:
b = np.empty(5)
b

array([  9.46698082e-312,   9.46697790e-312,   9.46697764e-312,
         9.46697763e-312,   9.46697857e-312])

In [15]:
np.multiply(a,b)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
x = np.arange(1,6)
np.add.reduce(x)

15

In [17]:
x

array([1, 2, 3, 4, 5])

In [18]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [19]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [20]:
np.meshgrid(x,x)
#This generates 

[array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]), array([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5]])]

In [20]:
x

array([1, 2, 3, 4, 5])

In [21]:
np.sum(x)

15

In [22]:
a = np.arange(1000000)

In [23]:
big_data = np.random.rand(10000000)

In [24]:
%timeit sum(big_data)

1 loop, best of 3: 2.58 s per loop


In [25]:
%timeit np.sum(big_data)

10 loops, best of 3: 42.9 ms per loop


In [22]:
x = np.random.random((3,4))
x

array([[ 0.06579144,  0.25370141,  0.30298342,  0.56350131],
       [ 0.45790394,  0.18487669,  0.36809216,  0.40414515],
       [ 0.92937821,  0.94946173,  0.354895  ,  0.36046558]])

In [24]:
np.sum(x,axis=1)

array([ 1.18597758,  1.41501794,  2.59420052])

In [27]:
np.sum(x,axis=0)

array([ 1.4530736 ,  1.38803983,  1.02597058,  1.32811204])

In [32]:
x

array([[ 0.28123493,  0.88694301,  0.58490254,  0.72500913],
       [ 0.26178834,  0.69518155,  0.57247881,  0.18224375],
       [ 0.22100612,  0.16971295,  0.82306808,  0.23825736]])

In [33]:
np.sum(x,axis=0)

array([ 0.76402939,  1.75183751,  1.98044943,  1.14551024])

In [30]:
x

array([[ 0.06579144,  0.25370141,  0.30298342,  0.56350131],
       [ 0.45790394,  0.18487669,  0.36809216,  0.40414515],
       [ 0.92937821,  0.94946173,  0.354895  ,  0.36046558]])

In [31]:
np.argmax(x,axis=1)

array([3, 0, 1], dtype=int64)

In [32]:
np.argmax(x)

9

In [35]:
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [2]:
x = np.array([-2,-1,11,3])

NameError: name 'np' is not defined

In [39]:
np.argmax(x)

2

In [5]:
x = np.array([1,2,3,4,5])

In [35]:
#Mask creation
x[x < 0.5]
#x[x < 3]

array([ 0.06579144,  0.25370141,  0.30298342,  0.45790394,  0.18487669,
        0.36809216,  0.40414515,  0.354895  ,  0.36046558])

In [6]:
x < 3

array([ True,  True, False, False, False], dtype=bool)

In [44]:
x[ x!= 3]

array([1, 2, 4, 5])

In [5]:
x = np.array([0,2,3,41,0,1])

In [46]:
np.count_nonzero(x)

4

In [47]:
np.any(x > 3)

True

In [49]:
np.all(x >= 0)

True

In [6]:
x

array([ 0,  2,  3, 41,  0,  1])

In [7]:
x[ (x<2) | ( x > 4)]

array([ 0, 41,  0,  1])

In [40]:
rand = np.random.RandomState(42)

In [41]:
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [42]:
rand = np.random.RandomState(42)
q = rand.randint(100, size=10)
q

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [11]:
ind = [2,3,4]

In [12]:
x[ind]

array([23,  2, 21])

In [13]:
x

array([87, 99, 23,  2, 21, 52,  1, 87, 29, 37])

In [7]:
row = np.array([0,1,2])
col = np.array([2,1,3])

In [9]:
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
X[row,col]

array([ 2,  5, 11])

In [20]:
row

array([0, 1, 2])

In [21]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
Y = np.arange(16).reshape((4,4))

In [24]:
Y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
Y[range(4),range(4)]

array([ 0,  5, 10, 15])

In [27]:
list(range(4))

[0, 1, 2, 3]

In [32]:
data = rand.randint(10000,size=100000000)

In [33]:
%timeit s = sorted(data)

1 loop, best of 3: 3min 59s per loop


In [34]:
%timeit s = np.sort(data)

1 loop, best of 3: 14.2 s per loop


In [43]:
data = np.random.randint(low=1,high=100,size=(2,4,8))

In [44]:
data

array([[[47, 91, 24, 67, 71, 27,  1, 76],
        [48, 87, 41, 45, 12, 15, 67, 99],
        [93, 97, 60, 37, 55, 31, 10, 93],
        [77, 64, 61, 27, 36, 16, 94, 49]],

       [[93, 20, 17, 29, 87, 29, 99, 87],
        [39, 13, 95, 51, 58, 96, 37, 95],
        [29, 98, 17, 50, 63, 72, 35, 20],
        [41,  8, 66, 62, 70, 76, 23, 99]]])