In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
titanic_data = pd.read_csv('titanic.csv')

In [5]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
#creates a mapping or logic that is capable of transformation
le.fit(titanic_data['Sex'])

LabelEncoder()

In [10]:
le.transform(titanic_data['Sex'])

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0,

In [14]:
titanic_data['Sex'] = le.fit_transform(titanic_data['Sex'])

In [15]:
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  Sex-t  
0         A/5 21171   7.2500   NaN        S      1  
1          PC 17599  71.2833   C85        C      0  
2  STON/O2. 3101282   7.9250   NaN        S      0  
3            113803  53.1000  C123        S      0  
4            373450   8.0500   NaN        S      1

In [16]:
del titanic_data['Sex-t']

In [33]:
titanic_data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   
5                                   Moran, Mr. James    1   NaN      0      0   
6                            McCarthy, Mr. Timothy J    1  54.0      0      0   
7                     Palsson, Master. Gosta Leonard    1   2.0      3      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    0  27.0      0      2   
9                Nasser, Mrs. Nicholas (Adele Achem)    0  14.0      1      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S  
5            330877   8.4583   NaN        Q  
6             17463  51.8625   E46        S  
7            349909  21.0750   NaN        S  
8            347742  11.1333   NaN        S  
9            237736  30.0708   NaN        C

In [18]:
cv = CountVectorizer()

In [22]:
tcv = cv.fit_transform(titanic_data['Name']).toarray()

In [23]:
tcv.shape

(891, 1509)

In [28]:
import numpy as np
np.where(tcv[0] == 1)

(array([ 177,  580, 1012, 1096], dtype=int64),)

In [32]:
np.where(tcv[5] >= 1)

(array([ 679, 1000, 1012], dtype=int64),)

In [41]:
(np.where(tcv[4] == 1)[0]).tolist()

[46, 610, 1012, 1479]

In [36]:
dict_data = cv.get_feature_names()

In [44]:
dict_data[[(np.where(tcv[4] == 1)[0]).tolist()]]

TypeError: list indices must be integers or slices, not list

In [49]:
dict_data

['aaron',
 'abbing',
 'abbott',
 'abelson',
 'abraham',
 'achem',
 'achille',
 'achilles',
 'ada',
 'adahl',
 'adams',
 'adelaide',
 'adele',
 'adelia',
 'adola',
 'adolf',
 'adolfina',
 'adolphe',
 'adrian',
 'agatha',
 'agda',
 'agnes',
 'ahlin',
 'ahmed',
 'aijo',
 'aime',
 'aina',
 'aks',
 'albert',
 'albimona',
 'albin',
 'albina',
 'alden',
 'alexander',
 'alexandra',
 'alexanteri',
 'alexenia',
 'alfons',
 'alfonzo',
 'alfred',
 'alfrida',
 'algernon',
 'alhomaki',
 'ali',
 'alice',
 'aline',
 'allen',
 'allison',
 'allum',
 'alma',
 'aloisia',
 'amanda',
 'ambrose',
 'amelia',
 'amelie',
 'amin',
 'amy',
 'anders',
 'andersen',
 'anderson',
 'andersson',
 'andre',
 'andreas',
 'andreasson',
 'andree',
 'andrew',
 'andrews',
 'andy',
 'angle',
 'ann',
 'anna',
 'anne',
 'annie',
 'anthony',
 'antino',
 'antoni',
 'antonine',
 'antti',
 'apostolos',
 'appleton',
 'archibald',
 'archie',
 'arne',
 'arnold',
 'artagaveytia',
 'arthur',
 'arvid',
 'asim',
 'asplund',
 'assad',
 'ass

In [51]:
new_cols = pd.DataFrame(columns=dict_data, data=tcv)

In [60]:
titanic_data.join(new_cols)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1   
2                               Heikkinen, Miss. Laina    0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1   
4                             Allen, Mr. William Henry    1  35.0      0   
5                                     Moran, Mr. James    1   NaN      0   
6                              McCarthy, Mr. Timothy J    1  54.0      0   
7                       Palsson, Master. Gosta Leonard    1   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    0  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)    0  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut    0   4.0      1   
11                            Bonnell, Miss. Elizabeth    0  58.0      0   
12                      Saundercock, Mr. William Henry    1  20.0      0   
13                         Andersson, Mr. Anders Johan    1  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina    0  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)     0  55.0      0   
16                                Rice, Master. Eugene    1   2.0      4   
17                        Williams, Mr. Charles Eugene    1   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...    0  31.0      1   
19                             Masselmani, Mrs. Fatima    0   NaN      0   
20                                Fynney, Mr. Joseph

In [61]:
pd.read_csv('Reviews.csv')

Id   ProductId          UserId  \
0            1  B001E4KFG0  A3SGXH7AUHU8GW   
1            2  B00813GRG4  A1D87F6ZCVE5NK   
2            3  B000LQOCH0   ABXLMWJIXXAIN   
3            4  B000UA0QIQ  A395BORC6FGVXV   
4            5  B006K2ZZ7K  A1UQRSCLF8GW1T   
5            6  B006K2ZZ7K   ADT0SRK1MGOEU   
6            7  B006K2ZZ7K  A1SP2KVKFXXRU1   
7            8  B006K2ZZ7K  A3JRGQVEQN31IQ   
8            9  B000E7L2R4  A1MZYO9TZK0BBI   
9           10  B00171APVA  A21BT40VZCCYT4   
10          11  B0001PB9FE  A3HDKO7OW0QNK4   
11          12  B0009XLVG0  A2725IB4YY9JEB   
12          13  B0009XLVG0   A327PCT23YH90   
13          14  B001GVISJM  A18ECVX2RJ7HUE   
14          15  B001GVISJM  A2MUGFV2TDQ47K   
15          16  B001GVISJM  A1CZX3CP8IKQIJ   
16          17  B001GVISJM  A3KLWF6WQ5BNYO   
17          18  B001GVISJM   AFKW14U97Z6QO   
18          19  B001GVISJM  A2A9X58G2GTBLP   
19          20  B001GVISJM  A3IV7CL2C13K2U   
20          21  B001GVISJM  A1WO0KGLPR5PV6   
21          22  B001GVISJM   AZOF9E17RGZH8   
22          23  B001GVISJM   ARYVQL4N737A1   
23          24  B001GVISJM   AJ613OLZZUG7V   
24          25  B001GVISJM  A22P2J09NJ9HKE   
25          26  B001GVISJM  A3FONPR03H3PJS   
26          27  B001GVISJM  A3RXAU2N8KV45G   
27          28  B001GVISJM   AAAS38B98HMIK   
28          29  B00144C10S  A2F4LZVGFLD1OB   
29          30  B0001PB9FY  A3HDKO7OW0QNK4   
...        ...         ...             ...   
568424  568425  B001FPT1WM  A291HTT117RVS9   
568425  568426  B001FPT1WM   A1TRJQBYQFZW4   
568426  568427  B001FPT1WM  A2F25C6QCKJ3HL   
568427  568428  B001FPT1WM   A7VLVCQJIROTF   
568428  568429  B001FPT1WM  A1YGG6T4YJZWC1   
568429  568430  B001FPT1WM   AW7HIV8I53FE4   
568430  568431  B001FPT1WM   A1XDMZMMOAMR7   
568431  568432  B003XUL27E  A32Y0419QFGVHM   
568432  568433  B003XUL27E  A1YKXVGAIA8952   
568433  568434  B003XUL27E  A1JUG9WCN1A52Z   
568434  568435  B003XUL27E   ABGQPE97ZVYJ3   
568435  568436  B003XUL27E  A2PSB4WQHH46HN   
568436  568437  B000NY4SAG  A3ODWHC3EMMWTT   
568437  568438  B000NY4SAG  A1RKKPSXF9QIZF   
568438  568439  B000NY4SAG  A3M89SF0SSOGBK   
568439  568440  B000NY4SAG  A34GDV49ZZQKXG   
568440  568441  B005ZC0RRO  A2TO5R8QLIITEF   
568441  568442  B000NY8O9M   AZRHU8CP5XKMF   
568442  568443  B006T7TKZO  A3BOURUK79CYY5   
568443  568444  B000H7K114  A2AGSSZR9V7XST   
568444  568445  B001EO7N10  A2SD7TY3IOX69B   
568445  568446  B001EO7N10  A2E5C8TTAED4CQ   
568446  568447  B001EO7N10  A2P9W8T7NTLG2Z   
568447  568448  B001EO7N10   APWCOAVILK94B   
568448  568449  B001EO7N10  A1F6BHEYB7R6R7   
568449  568450  B001EO7N10  A28KG5XORO54AY   
568450  568451  B003S1WTCU  A3I8AFVPEE8KI5   
568451  568452  B004I613EE  A121AA1GQV751Z   
568452  568453  B004I613EE   A3IBEVCTXKNOH   
568453  568454  B001LR2CU2  A3LGQPJCZVL9UC   

                                 ProfileName  HelpfulnessNumerator  \
0                                 delmartian                     1   
1                                     dll pa                     0   
2            Natalia Corres "Natalia Corres"                     1   
3                                       Karl                     3   
4              Michael D. Bigham "M. Wassir"                     0   
5                             Twoapennything                     0   
6                          David C. Sullivan                     0   
7                         Pamela G. Williams                     0   
8                                   R. James                     1   
9                              Carol A. Reed                     0   
10                              Canadian Fan                     1   
11                    A Poeng "SparkyGoHome"                     4   
12                                        LT                     1   
13                           willie "roadie"                     2   
14                       Lynrie "Oh HELL no"                     4   
15                              Brian A