* To store n-dim data which is required for machine learning
* Low level library using which, scikit-learn provides machine learning functionality
* Homogenous data structure

In [2]:
import numpy as np

In [2]:
l = [ [1,2,3], [4,'five',6.9]]

##### Problems that NumPy solves in Python List
* Python list is collection of references - benefit is that, it becomes a generic datastorage
* Shortcomings - It becomes slower.

##### What is NumPy doing here ?
* It's more like a C-array which holds the value itself.
* Because of this, it becomes specfic & holds same type of data
* It is implemented using C
* NumPy storage is mutable


### Data Creation

In [3]:
#Pass list to array for nparray creation
a = np.array([1,2,3,4,4,5])

In [4]:
a

array([1, 2, 3, 4, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
a[0] = 11

In [7]:
a

array([11,  2,  3,  4,  4,  5])

In [8]:
a

array([11,  2,  3,  4,  4,  5])

In [6]:
b = np.arange(10)

In [7]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
range(10)

range(0, 10)

In [12]:
np.array([1,2,3,4],dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [13]:
np.array([1.2,3,4])

array([ 1.2,  3. ,  4. ])

In [15]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [19]:
np.ones((2,3,4,5))

array([[[[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]]],


       [[[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.]]]])

In [20]:
np.full((2,4),5.5)

array([[ 5.5,  5.5,  5.5,  5.5],
       [ 5.5,  5.5,  5.5,  5.5]])

In [21]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [9]:
np.random.randint(5,10)

8

In [10]:
#Diemsions will always be in tuple
np.random.random((2,4))

array([[ 0.38495412,  0.6223774 ,  0.69298051,  0.99456143],
       [ 0.5830863 ,  0.33508511,  0.76096116,  0.08947125]])

In [37]:
np.random.normal(1,10,(5,5))

array([[ -5.12969303,   9.32595956,  -2.83397768,  -0.02955646,
         -4.41101775],
       [ -6.04918274,  -2.97827146,   2.1617591 ,   8.77034575,
         -1.99085386],
       [ -3.11189635,   2.42833029,  13.25341453, -16.95771933,
         -4.75293648],
       [ -4.29396839,   3.14673651,  -2.29724623,  -5.13502312,  -0.9368287 ],
       [ -4.35085916,  -3.76288288,  12.26241379,  13.79506479,
         -3.40693124]])

In [33]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [11]:
data = np.random.randint(0,10,(3,4))

In [12]:
data

array([[2, 7, 3, 8],
       [3, 7, 0, 1],
       [3, 0, 7, 9]])

### Basic of NumPy

In [18]:
#Seed controlls randomness, same seed means same random numbers
np.random.seed(10)

In [14]:
np.random.randint(10,size=6)

array([9, 4, 0, 1, 9, 0])

In [17]:
np.random.seed(1)
np.random.randint(10,size=6)

array([5, 8, 9, 5, 0, 0])

In [19]:
data.ndim

2

In [48]:
data

array([[1, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [20]:
data.shape

(3, 4)

In [50]:
data.size

12

In [56]:
data[1][2]

4

In [21]:
d = np.arange(10)

In [55]:
d[2:5]

array([2, 3, 4])

In [22]:
x = d.reshape((2,5))

In [23]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x.shape

(2, 5)

In [25]:
x = np.array([1,2,3])

In [29]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [31]:
data.T

array([[2, 3, 3],
       [7, 7, 0],
       [3, 0, 7],
       [8, 1, 9]])

In [63]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [64]:
x

array([1, 2, 3])

In [65]:
x.T

array([1, 2, 3])

In [66]:
data

array([[1, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [67]:
data.T

array([[1, 8, 0],
       [8, 6, 4],
       [9, 4, 6],
       [0, 3, 8]])

#### Concatination & Splitting of Arrays

In [35]:
x = np.array([1,2,3,np.nan])
y = np.array([4,5,6,9])

In [36]:
np.concatenate([x,y])

array([  1.,   2.,   3.,  nan,   4.,   5.,   6.,   9.])

In [37]:
x + y

array([  5.,   7.,   9.,  nan])

In [71]:
x * y

array([ 4, 10, 18])

In [72]:
g = np.array([ [1,2,3], 
               [4,5,6]])

In [73]:
np.concatenate([g,g])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
g

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
## Axis 1 - Horizontal
## Axis 0 - Vertical

In [76]:
np.concatenate([g,g], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [77]:
h = np.array([ [1,2,3], 
               [4,5,6], 
               [6,7,8]
             ])

In [78]:
np.concatenate([g,h])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [80]:
#np.concatenate([g,h],axis=1)
#This will not work, since they dont have same height

In [81]:
h

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [82]:
g

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
data = np.arange(16).reshape((4,4))

In [85]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
d1 , d2 = np.vsplit(data,[2])

In [88]:
d1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
d2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.hsplit(data,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### Computation

In [91]:
d = np.arange(10)


In [92]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
2 * d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
2 ** d

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [39]:
d ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [95]:
d + 5 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
d = np.arange(1000000)

In [96]:
np.add(d,5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
%timeit np.sum(d)

1000 loops, best of 3: 1.07 ms per loop


In [48]:
%timeit sum(d)

C:\Users\ZekeLabs\Anaconda3\lib\site-packages\ipykernel_launcher.py:257: RuntimeWarning: overflow encountered in long_scalars


1 loop, best of 3: 162 ms per loop
