In [1]:
import numpy as np

In [3]:
L = np.random.random(100)

In [4]:
%timeit sum(L)

10000 loops, best of 3: 24.6 µs per loop


In [5]:
%timeit np.sum(L)

The slowest run took 14.59 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.23 µs per loop


In [6]:
min(L)

0.006092884087239514

In [12]:
%timeit np.min(L)

The slowest run took 11.06 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.32 µs per loop


In [11]:
%timeit L.min()

The slowest run took 11.99 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.76 µs per loop


In [13]:
L

array([ 0.59762232,  0.40157474,  0.42864852,  0.36257017,  0.64196681,
        0.32193427,  0.90848202,  0.72276555,  0.67138131,  0.75598732,
        0.28481867,  0.96736327,  0.24396544,  0.90895896,  0.65683281,
        0.8728343 ,  0.4042383 ,  0.83431212,  0.42378604,  0.3316446 ,
        0.44927819,  0.96443112,  0.12868223,  0.06941841,  0.62867606,
        0.51467174,  0.22752841,  0.21168768,  0.995028  ,  0.78057568,
        0.42436452,  0.99971015,  0.19138767,  0.1821426 ,  0.42348629,
        0.87975825,  0.60241557,  0.91394513,  0.88709218,  0.07643762,
        0.77470008,  0.44503722,  0.12576938,  0.87859488,  0.13302676,
        0.23085521,  0.11201167,  0.21504282,  0.44883861,  0.57170936,
        0.28841328,  0.4319974 ,  0.24481623,  0.1518047 ,  0.31835686,
        0.00609288,  0.30953192,  0.25852794,  0.72015503,  0.62726792,
        0.59076116,  0.80940304,  0.29270523,  0.29274198,  0.10089274,
        0.1981226 ,  0.1652087 ,  0.0122724 ,  0.27511959,  0.35

#### Multi dimensional aggregates

In [2]:
M = np.random.random((3,4))

In [3]:
M

array([[ 0.08677953,  0.91595457,  0.79953993,  0.64044541],
       [ 0.21548113,  0.94530887,  0.36114093,  0.07270983],
       [ 0.91639202,  0.96395223,  0.91345433,  0.78200924]])

In [16]:
np.sum(M,axis=1)

array([ 2.14835089,  2.41310974,  1.67422818])

In [17]:
np.max(M,axis=1)

array([ 0.87964558,  0.86281712,  0.84743185])

In [18]:
np.max(M,axis=0)

array([ 0.87964558,  0.72428475,  0.86281712,  0.79662629])

In [19]:
K = np.array([3,4,6,7,71])

In [20]:
#Index of max value
np.argmax(K)

4

In [22]:
#Index of min value
np.argmin(K)

0

In [23]:
np.mean(K)

18.199999999999999

In [24]:
np.std(K)

26.437851652507621

In [25]:
np.median(K)

6.0

In [26]:
D = np.array([1,0,2,3])

In [28]:
#Returns TRue if all elements are non-zero
np.all(D)

False

In [29]:
#Returns True if any of the element non-zero
np.any(D)

True

### Comparisons, Masks & Boolean Logic

In [8]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
x[x < 5]

array([1, 2, 3, 4])

In [32]:
x[x < 5]

array([1, 2, 3, 4])

In [34]:
#Returns mask array on using comparsion operator
x < 5

array([ True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [38]:
#If logic1 or logic2 is true, have True in Mask array
x[(x < 5) | (x > 8)]

array([1, 2, 3, 4, 9])

In [40]:
x[(x < 5) | (x > 8)]

array([1, 2, 3, 4, 9])

In [41]:
x[ (x%10==0) & (x%15==0)]

45

In [11]:
#1 & 3 are the index of the data which we want to fetch
x[np.array([1,3])]

array([2, 4])

In [43]:
8 and 10

10

In [44]:
bin(8)

'0b1000'

In [45]:
bin(10)

'0b1010'

In [46]:
bin(8 or 10)

'0b1000'

In [47]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
indx = [3,4,8]

In [50]:
x[indx]

array([4, 5, 9])

In [12]:
import numpy as np
M = np.random.randint(1,100,(5,5))

In [13]:
M

array([[55, 73, 83, 44, 31],
       [45, 89, 59, 41, 67],
       [36, 33, 94, 71, 83],
       [33, 23, 41, 63,  8],
       [55, 71, 24, 97, 72]])

In [13]:
indx = np.array([ [1], [2] ])
indx

array([[1],
       [2]])

In [21]:
data = M[indx]
data

array([[[44, 18, 15, 61, 34]],

       [[61, 60, 73, 60, 16]]])

In [23]:
M[1]

array([44, 18, 15, 61, 34])

In [14]:
M[np.arange(1,5,2)]
#Generate indices programmatically

array([[45, 89, 59, 41, 67],
       [33, 23, 41, 63,  8]])

In [6]:
# Create a 
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Adds one more dimension
d[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
d.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [15]:
X = np.arange(12).reshape((3,4))

In [81]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
#np.newaxis will add one more dimension
X[:,np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [19]:
x = np.array([1,2,3,4])

In [21]:
x[:,np.newaxis][:,np.newaxis]

array([[[1]],

       [[2]],

       [[3]],

       [[4]]])

In [84]:
X[:,np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [9]:
X.transpose()
#Converts rows to column & column to rows

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
X.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [89]:
l = (1,)

In [90]:
type(l)

tuple

In [91]:
l = (1)

In [92]:
type(l)

int

#### sort and argsort

In [95]:
np.sort(np.array([2,1,1,1,3]))

array([1, 1, 1, 2, 3])

In [96]:
np.argsort(np.array([2,1,1,1,3]))
#Returns index of sorted data

array([1, 2, 3, 0, 4], dtype=int64)

In [98]:
M

array([[97, 27, 61, 83, 57],
       [27, 65, 10, 26, 96],
       [38, 33, 19, 58, 71],
       [92, 63, 96, 76, 16],
       [81, 76,  9, 92, 70]])

In [99]:
#axis 1 - sorting row wise
np.sort(M,axis=1)

array([[27, 57, 61, 83, 97],
       [10, 26, 27, 65, 96],
       [19, 33, 38, 58, 71],
       [16, 63, 76, 92, 96],
       [ 9, 70, 76, 81, 92]])

In [101]:
#axis 0 - sorting col wise
np.sort(M,axis=0)

array([[27, 27,  9, 26, 16],
       [38, 33, 10, 58, 57],
       [81, 63, 19, 76, 70],
       [92, 65, 61, 83, 71],
       [97, 76, 96, 92, 96]])

In [1]:
import numpy as np

In [3]:
d = np.random.randint(1,100,(5,5))

In [4]:
d

array([[42, 32, 14, 34,  8],
       [70, 82, 25, 79, 77],
       [42, 82, 52, 86, 75],
       [96, 76, 76, 24,  3],
       [37, 83, 89, 22, 91]])

In [7]:
d[:,1:4]

array([[32, 14, 34],
       [82, 25, 79],
       [82, 52, 86],
       [76, 76, 24],
       [83, 89, 22]])