### Defination
Machine Learning By examples

* Supervised - Regression & Classification
* Unsepervised - Relationship amaong data, Clustering  & Dimensionality reduction

#### Scikit-Learn
* Provides large number of common algorithms

In [2]:
### Data representation in scikit-learn

import seaborn as sns
iris = sns.load_dataset('iris')

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
iris.shape

(150, 5)

#### Supervised Learning Example : Simple linear Regression

In [5]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [6]:
rng = np.random.RandomState(11)

In [7]:
x = 10 * rng.rand(50)

In [9]:
y = 2*x + 1.5

In [10]:
y

array([  5.10539378,   1.88950483,  10.76437053,  15.99867858,
         9.90407209,  11.20854196,   1.75561629,  11.24743215,
        20.33613305,  18.51590179,  16.0992894 ,   3.67472144,
        19.37808341,  18.64308494,   4.80173235,  14.14668028,
         1.90967226,   3.83474538,   7.82734623,   4.65824613,
        16.67959176,  17.86550716,   8.39248982,   7.87597594,
         3.73322464,   3.17906287,  15.75451871,  13.49086793,
         2.61347359,  11.09594563,   9.53352961,  18.45957995,
        15.85698359,  13.54128102,  12.54767643,  20.48204795,
        21.23346661,   8.26108099,   6.29749358,  17.42871508,
         2.77372862,   8.79231286,   2.90045605,   7.88735414,
         2.9076519 ,   7.30527334,  17.30202247,  19.60800642,
        17.3524277 ,  12.7363742 ])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression(fit_intercept=True)

In [17]:
#Trained the model with feature & target
#Input data should be in form of list of rows
model.fit(x[:,np.newaxis],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
x[:,np.newaxis]

array([[ 1.80269689],
       [ 0.19475241],
       [ 4.63218526],
       [ 7.24933929],
       [ 4.20203605],
       [ 4.85427098],
       [ 0.12780815],
       [ 4.87371607],
       [ 9.41806652],
       [ 8.50795089],
       [ 7.2996447 ],
       [ 1.08736072],
       [ 8.9390417 ],
       [ 8.57154247],
       [ 1.65086618],
       [ 6.32334014],
       [ 0.20483613],
       [ 1.16737269],
       [ 3.16367312],
       [ 1.57912307],
       [ 7.58979588],
       [ 8.18275358],
       [ 3.44624491],
       [ 3.18798797],
       [ 1.11661232],
       [ 0.83953143],
       [ 7.12725936],
       [ 5.99543396],
       [ 0.5567368 ],
       [ 4.79797282],
       [ 4.01676481],
       [ 8.47978998],
       [ 7.17849179],
       [ 6.02064051],
       [ 5.52383822],
       [ 9.49102398],
       [ 9.8667333 ],
       [ 3.3805405 ],
       [ 2.39874679],
       [ 7.96435754],
       [ 0.63686431],
       [ 3.64615643],
       [ 0.70022803],
       [ 3.19367707],
       [ 0.70382595],
       [ 2

In [19]:
model.coef_

array([ 2.])

In [20]:
model.intercept_

1.5000000000000018