### NumPy ( Numerical Python )
* List, Dictionary  etc. are genral purpose storage mechanism.
* NumPy is specialized software
* Storage for ndim data
* Have lot of methods to make ndim data processing easier
* Very fast - C like storage
* Homogenous data storage - same type of data
* mutable

NumPy Storage - [ A ]-[ B ]-[ C ]
List Store - [] -[] -[]
              |   |
              V   V
              Data

In [1]:
# Importing NumPy
# To Propcess an image, of size 1024 X 1024. You have to store it in 1024 X 1024 ~ 10^6 dimension
# NumPy is capable of storing & processing such complex data structure
import numpy as np

#### Creating NumPy storage

##### Creating Arrays from Python List

In [2]:
# Creating a list
l = [1,2,3,4,5]

# Creating Arrays from Python List - converting list into python np.array
np_data = np.array(l)

In [3]:
np_data

array([1, 2, 3, 4, 5])

In [44]:

#NumPy provides, storage mechanism & lot of functionalities

#### Creating ndarray with 0's & 1's

In [3]:
#Creating from scratch
#dtype - data type of the initialized data
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
d = np.zeros((4,3),dtype=int)
help(np.zeros)
#If you don't specify datatype - it will take as float
#Sizes are always passed in tuple format

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [5]:
d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones((5,5,5))
#sizes of more than 1d will be passed in tuple

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [14]:
#Initlizes a matrix with given data 
np.full((5,5),"sixtysix")

array([['sixtysix', 'sixtysix', 'sixtysix', 'sixtysix', 'sixtysix'],
       ['sixtysix', 'sixtysix', 'sixtysix', 'sixtysix', 'sixtysix'],
       ['sixtysix', 'sixtysix', 'sixtysix', 'sixtysix', 'sixtysix'],
       ['sixtysix', 'sixtysix', 'sixtysix', 'sixtysix', 'sixtysix'],
       ['sixtysix', 'sixtysix', 'sixtysix', 'sixtysix', 'sixtysix']], 
      dtype='<U8')

In [7]:
#Generates all numbers between start & end data with proper spacing.
np.arange(10,100,5)
#list(range(10,20))

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [18]:
np.linspace(5,10,20)
#Between 5 to 10, it generated 20 equal spaced numbers

array([  5.        ,   5.26315789,   5.52631579,   5.78947368,
         6.05263158,   6.31578947,   6.57894737,   6.84210526,
         7.10526316,   7.36842105,   7.63157895,   7.89473684,
         8.15789474,   8.42105263,   8.68421053,   8.94736842,
         9.21052632,   9.47368421,   9.73684211,  10.        ])

In [3]:
#Generates matrix with 4 X 4 with all random numbers
a = np.random.random((4,4))
a

array([[ 0.67923979,  0.51065475,  0.1635249 ,  0.0958692 ],
       [ 0.18785012,  0.88521584,  0.56962546,  0.75576486],
       [ 0.41027062,  0.82464306,  0.31895919,  0.4362136 ],
       [ 0.44870012,  0.7297397 ,  0.0815735 ,  0.02103317]])

In [8]:
#Seed controls random number generation
#Everytime, you have same seed, it will generate same seq of random numbers
np.random.seed(2)
#genrates random number between 2 & 5 of size (2,3)
np.random.randint(2,5,size=(2,3))
# seed controls the order of random number genration

array([[2, 3, 2],
       [4, 4, 2]])

In [5]:
np.random.randint(0,10,size=(3,3))

array([[0, 1, 7],
       [6, 9, 2],
       [4, 5, 2]])

### Accessing Elements

In [18]:
#Generating 5 units of data between 0 to 10
data = np.random.randint(0,10,size=5)

In [19]:
data

array([7, 2, 8, 0, 0])

In [20]:
data[0]

7

In [21]:
data[-1]

0

In [22]:
data[2:5]

array([5, 9, 3])

In [9]:
ndata = np.random.randint(0,10,size=(4,5))
ndata

array([[7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6],
       [4, 3, 7, 6, 1],
       [3, 5, 8, 4, 6]])

In [6]:
ndata[1,1]

0

In [25]:
ndata

array([[4, 2, 1, 5, 5],
       [7, 4, 1, 8, 8],
       [1, 3, 6, 2, 2],
       [0, 0, 7, 6, 9]])

In [8]:
# altering contents
ndata[1,1] = 9999
ndata

array([[   9,    5,    9,    0,    3],
       [   8, 9999,    0,    3,    8],
       [   2,    9,    1,    2,    4],
       [   4,    8,    9,    6,    6]])

In [ ]:
import numpy as np

In [26]:
ndata

array([[4, 2, 1, 5, 5],
       [7, 4, 1, 8, 8],
       [1, 3, 6, 2, 2],
       [0, 0, 7, 6, 9]])

In [72]:
ndata[1][2] = 8888

In [73]:
ndata

array([[   0,    0,    6,    9,    1],
       [   8, 9999, 8888,    2,    8],
       [   9,    9,    5,    0,    2],
       [   7,    3,    0,    4,    2]])

In [28]:
#### Genrating same seq of random numbers



In [76]:
np.random.seed(10) # 
np.random.randint(10,size=5)

array([9, 4, 0, 1, 9])

In [30]:
np.random.seed(10)
np.random.randint(10,size=5)

array([9, 4, 0, 1, 9])

In [27]:
ndata

array([[4, 2, 1, 5, 5],
       [7, 4, 1, 8, 8],
       [1, 3, 6, 2, 2],
       [0, 0, 7, 6, 9]])

In [28]:
ndata[:2]

array([[4, 2, 1, 5, 5],
       [7, 4, 1, 8, 8]])

In [14]:
ndata

array([[0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4],
       [2, 4, 7, 7, 9],
       [1, 7, 0, 6, 9]])

In [17]:
ndata[1:3,2:4]

array([[5, 2],
       [7, 7]])

In [9]:
ndata[1:3,2:4]

array([[0, 3],
       [1, 2]])

In [11]:
ndata

array([[7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6],
       [4, 3, 7, 6, 1],
       [3, 5, 8, 4, 6]])

In [10]:
ndata[-3:-2]

array([[4, 5, 7, 3, 6]])

In [36]:
ndata

array([[   4,    7,    1,    4,    3],
       [   4, 9999,    7,    6,    4],
       [   2,    5,    6,    7,    1],
       [   6,    3,    5,    8,    7]])

### Reshaping of Arrays
* Changing dimension of NumPy array
* shape - size at each dim
* size - total num of elems
* ndim - total num of dimensions

In [12]:
data = np.arange(0,10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#shape - dimension information along with size 
data.shape

(10,)

In [12]:
data = data.reshape((1,10))
data


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
data.ndim

1

In [37]:
data.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
#This is the number of elems
data.size

10

In [40]:
#Tells number of dimensions
data.ndim


1

In [41]:
ndata = data.reshape((2,5))

In [42]:
ndata.shape

(2, 5)

In [43]:
ndata.ndim

2

In [44]:
ndata.size

10

In [45]:
ndata

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
print('hello')

hello


In [ ]:
import numpy as np