#### What is BIg Data ?

4 V's of Big Data
* Velocity 
* Volume 
* Variety 
* Veracity

Pandas - High-Performance open source library for data analysis
* Process datasets of different formats - time series, tabular data, matrix data
* Import data from csv,json & database
* Provides extensive operations like slice,subset,merging, groupby,shaping etc.
* Handling missing data
* Doing statiscal analysis
* Pandas objects are consumed by scikit-learn,tensorflow


In [17]:
import pandas as pd

#### Two main datastructure inside pandas
* Series - Column or associative array
* DataFrame - Table or collection of series


##### Series
1D NumPy array with name

In [18]:
import pandas as pd
import numpy as np

In [19]:
ser = pd.Series(np.random.rand(8),index= ['a','b','c','d','e','f','g','c'],dtype=float)

In [20]:
ser['c']

c    0.911356
c    0.862684
dtype: float64

In [21]:
ser

a    0.195505
b    0.774304
c    0.911356
d    0.797405
e    0.081148
f    0.572318
g    0.184799
c    0.862684
dtype: float64

In [22]:
ser.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'c'], dtype='object')

In [23]:
ser.values

array([ 0.19550502,  0.77430421,  0.91135563,  0.79740545,  0.08114796,
        0.57231816,  0.18479927,  0.86268426])

In [24]:
#### Series creation from dictionary - key becomes index
db = {'US':'dollar','India':'rupee','UK':'euro'}

In [25]:
currSer = pd.Series(db)

In [26]:
currSer

India     rupee
UK         euro
US       dollar
dtype: object

In [27]:
currSer['UK']

'euro'

In [28]:
### Create Series from Scalar values

In [29]:
dogseries = pd.Series('xyz',index=['breed','location'])

In [30]:
pd.Series(0, index=[1,2,3,4])

1    0
2    0
3    0
4    0
dtype: int64

In [31]:
dogseries

breed       xyz
location    xyz
dtype: object

In [32]:
pd.Series(np.arange(7), index=['a','b','c','d','e','f','g'])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int32

In [33]:
ser = pd.Series(np.random.rand(7), index=['a','b','c','d','e','f','g'])

In [34]:
ser2 = pd.Series(np.random.rand(7))

In [35]:
ser2[:3]

0    0.804744
1    0.055690
2    0.383110
dtype: float64

In [36]:
ser

a    0.777556
b    0.098141
c    0.420753
d    0.932742
e    0.288086
f    0.661859
g    0.392400
dtype: float64

In [37]:
# Opeartions on series
# Imp - last elem is inclusive
ser[:'c']

a    0.777556
b    0.098141
c    0.420753
dtype: float64

In [38]:
ser['c'] = 22222.0

In [39]:
ser

a        0.777556
b        0.098141
c    22222.000000
d        0.932742
e        0.288086
f        0.661859
g        0.392400
dtype: float64

In [40]:
np.mean(ser)

3175.021540598719

In [41]:
np.std(ser)

7775.896399188608

In [42]:
np.random.choice(5,12)

array([1, 3, 1, 1, 1, 0, 2, 4, 2, 3, 4, 4])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### DataFrames
* Analogous to spreedsheet
* collection series
* mutable - contents changeable
* hetrogenous - different cols with different type of data

#### Most commonly used data structure in pandas
* Dic of 1D arrays,series
* NumPy array
* csv, json, databases


In [44]:
#Dictionary of Series
#Key of dictionary becomes column name
#Value of dictionary becomes column
stockSummaries={
    
'AMZN': pd.Series([346.15,0.59,459,0.52,589.8,158.88], 
        index=['Closing price','EPS',
                'Shares Outstanding(M)',
                'Beta', 'P/E','Market Cap(B)']),
    
'GOOG': pd.Series([1133.43,36.05,335.83,0.87,31.44,380.64],
        index=['Closing price','EPS','Shares Outstanding(M)',
               'Beta','P/E','Market Cap(B)']),
    
'FB': pd.Series([61.48,0.59,2450,104.93,150.92], 
      index=['Closing price','EPS','Shares Outstanding(M)',
             'P/E', 'Market Cap(B)']),
    
'YHOO': pd.Series([34.90,1.27,1010,27.48,0.66,35.36],
        index=['Closing price','EPS','Shares Outstanding(M)',
               'P/E','Beta', 'Market Cap(B)']),
    
'TWTR':pd.Series([65.25,-0.3,555.2,36.23],
       index=['Closing price','EPS','Shares Outstanding(M)',
              'Market Cap(B)']), 
    
'AAPL':pd.Series([501.53,40.32,892.45,12.44,447.59,0.84],
       index=['Closing price','EPS','Shares Outstanding(M)','P/E',
              'Market Cap(B)','Beta'])}

In [45]:
stockdf = pd.DataFrame(stockSummaries)

In [46]:
stockdf

AAPL    AMZN       FB     GOOG    TWTR     YHOO
Beta                     0.84    0.52      NaN     0.87     NaN     0.66
Closing price          501.53  346.15    61.48  1133.43   65.25    34.90
EPS                     40.32    0.59     0.59    36.05   -0.30     1.27
Market Cap(B)          447.59  158.88   150.92   380.64   36.23    35.36
P/E                     12.44  589.80   104.93    31.44     NaN    27.48
Shares Outstanding(M)  892.45  459.00  2450.00   335.83  555.20  1010.00

In [47]:
#This will not change the stickdf, just return to display
stockdf.T

Beta  Closing price    EPS  Market Cap(B)     P/E  Shares Outstanding(M)
AAPL  0.84         501.53  40.32         447.59   12.44                 892.45
AMZN  0.52         346.15   0.59         158.88  589.80                 459.00
FB     NaN          61.48   0.59         150.92  104.93                2450.00
GOOG  0.87        1133.43  36.05         380.64   31.44                 335.83
TWTR   NaN          65.25  -0.30          36.23     NaN                 555.20
YHOO  0.66          34.90   1.27          35.36   27.48                1010.00

In [48]:
#Accessing column with single braces returns a series
stockdf['AAPL']

Beta                       0.84
Closing price            501.53
EPS                       40.32
Market Cap(B)            447.59
P/E                       12.44
Shares Outstanding(M)    892.45
Name: AAPL, dtype: float64

In [49]:
#Accessing with double [[]] returns dataframe
stockdf[['AAPL']]

AAPL
Beta                     0.84
Closing price          501.53
EPS                     40.32
Market Cap(B)          447.59
P/E                     12.44
Shares Outstanding(M)  892.45

In [50]:
type(stockdf['AAPL'])

pandas.core.series.Series

In [51]:
stockdf[['AAPL','FB']]

AAPL       FB
Beta                     0.84      NaN
Closing price          501.53    61.48
EPS                     40.32     0.59
Market Cap(B)          447.59   150.92
P/E                     12.44   104.93
Shares Outstanding(M)  892.45  2450.00

In [52]:
#returns a dataframe
stockdf[['AAPL']]

AAPL
Beta                     0.84
Closing price          501.53
EPS                     40.32
Market Cap(B)          447.59
P/E                     12.44
Shares Outstanding(M)  892.45

In [53]:
#column deletion
del stockdf['AAPL']

In [54]:
stockdf

AMZN       FB     GOOG    TWTR     YHOO
Beta                     0.52      NaN     0.87     NaN     0.66
Closing price          346.15    61.48  1133.43   65.25    34.90
EPS                      0.59     0.59    36.05   -0.30     1.27
Market Cap(B)          158.88   150.92   380.64   36.23    35.36
P/E                    589.80   104.93    31.44     NaN    27.48
Shares Outstanding(M)  459.00  2450.00   335.83  555.20  1010.00

In [55]:
#Creating a new column from values of other column
stockdf['ZEKE'] = stockdf['GOOG'] + 100

In [59]:
stockdf[['TWTR']].fillna(0)

TWTR
Beta                     0.00
Closing price           65.25
EPS                     -0.30
Market Cap(B)           36.23
P/E                      0.00
Shares Outstanding(M)  555.20

In [60]:
#Creating dataframe from numpy array
ore1DF=pd.DataFrame(np.array([[20,35,25,20],
                              [11,28,32,29]]),
                    columns=['iron','magnesium',
                             'copper','silver'],
                    index=['a','b'])

In [49]:
ore1DF

iron  magnesium  copper  silver
a    20         35      25      20
b    11         28      32      29

In [11]:
#Create dataframe from dic of series
df1 = pd.DataFrame({ 'abc': pd.Series([1,2,3,4], index=['a','b','c','e']), 
                     'def': pd.Series([5,6,7,8], index=['a','b','c','d'])
                   }
             )
df1

abc  def
a  1.0  5.0
b  2.0  6.0
c  3.0  7.0
d  NaN  8.0
e  4.0  NaN

In [28]:
df2 = pd.DataFrame({ 'abc': pd.Series([1,2,3,4], index=['a','b','c','e']), 
                     'def': pd.Series([5,6,7,8], index=['a','b','c','d'])}
             )

df3 = pd.DataFrame({ 'abc': pd.Series([1,2,3,4], index=['a','b','c','e'])})

df2

abc  def
a  1.0  5.0
b  2.0  6.0
c  3.0  7.0
d  NaN  8.0
e  4.0  NaN

In [18]:
df2['def'].index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [19]:
df2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [20]:
df2

abc  def
a  1.0  5.0
b  2.0  6.0
c  3.0  7.0
d  NaN  8.0
e  4.0  NaN

In [21]:
df3

abc
a    1
b    2
c    3
e    4

In [17]:
df2 + df3

abc  def
a  2.0  NaN
b  4.0  NaN
c  6.0  NaN
d  NaN  NaN
e  8.0  NaN

In [29]:
df3['def'] = pd.Series(0, df3.index)
df3

abc  def
a    1    0
b    2    0
c    3    0
e    4    0

In [30]:
df2

abc  def
a  1.0  5.0
b  2.0  6.0
c  3.0  7.0
d  NaN  8.0
e  4.0  NaN

In [14]:
df3

abc  def
a    1    0
b    2    0
c    3    0
e    4    0

In [18]:
df2 + df3

abc  def
a  2.0  5.0
b  4.0  6.0
c  6.0  7.0
d  NaN  NaN
e  8.0  NaN

In [59]:
np.sqrt(df1)

abc       def
a  1.000000  2.236068
b  1.414214  2.449490
c  1.732051  2.645751
d       NaN  2.828427
e  2.000000       NaN

In [19]:
l = [1,2,3]

In [21]:
list(map(lambda x:x+2, l))

[3, 4, 5]

In [61]:
stockdf.describe()

AMZN          FB         GOOG        TWTR         YHOO  \
count    6.000000     5.00000     6.000000    4.000000     6.000000   
mean   259.156667   553.58400   319.710000  164.095000   184.945000   
std    245.208184  1061.57796   431.586397  262.112336   404.499103   
min      0.520000     0.59000     0.870000   -0.300000     0.660000   
25%     40.162500    61.48000    32.592500   27.097500     7.822500   
50%    252.515000   104.93000   185.940000   50.740000    31.190000   
75%    430.787500   150.92000   369.437500  187.737500    35.245000   
max    589.800000  2450.00000  1133.430000  555.200000  1010.000000   

              ZEKE  
count     6.000000  
mean    419.710000  
std     431.586397  
min     100.870000  
25%     132.592500  
50%     285.940000  
75%     469.437500  
max    1233.430000

In [62]:
stockdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Beta to Shares Outstanding(M)
Data columns (total 6 columns):
AMZN    6 non-null float64
FB      5 non-null float64
GOOG    6 non-null float64
TWTR    4 non-null float64
YHOO    6 non-null float64
ZEKE    6 non-null float64
dtypes: float64(6)
memory usage: 496.0+ bytes
