In [1]:
import numpy as np

In [3]:
data = np.arange(10)

In [4]:
data.shape

(10,)

In [5]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
new_data = data.reshape((10,1))

In [8]:
new_data

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
data.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
data.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array Concatenation & Splitting

In [13]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [14]:
xx = np.array([ [1,2,3], [4,5,6], [7,8,9]])

In [15]:
np.concatenate([xx,xx])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.concatenate([xx,xx],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [18]:
x

array([1, 2, 3])

In [19]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#Stacking vertically
np.vstack([x,xx])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#Stacking horizontally
np.hstack([xx,xx])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

#### Splitting arrays

In [24]:
x = [1,2,3,4,5,6,67,7]

In [27]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([ 6, 67,  7])]

In [28]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#Splits the vertical axis
np.vsplit(xx,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [33]:
a,b = np.hsplit(xx,[1])

In [34]:
a

array([[1],
       [4],
       [7]])

In [35]:
b

array([[2, 3],
       [5, 6],
       [8, 9]])

#### Computation on NumPy Arrays

In [36]:
d = np.arange(100)

In [37]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
d + 5

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104])

In [43]:
np.concatenate([d[:50] * 2, d[50:]])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
d[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
d / 2

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,
        13.5,  14. ,  14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,
        18. ,  18.5,  19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,
        22.5,  23. ,  23.5,  24. ,  24.5,  25. ,  25.5,  26. ,  26.5,
        27. ,  27.5,  28. ,  28.5,  29. ,  29.5,  30. ,  30.5,  31. ,
        31.5,  32. ,  32.5,  33. ,  33.5,  34. ,  34.5,  35. ,  35.5,
        36. ,  36.5,  37. ,  37.5,  38. ,  38.5,  39. ,  39.5,  40. ,
        40.5,  41. ,  41.5,  42. ,  42.5,  43. ,  43.5,  44. ,  44.5,
        45. ,  45.5,  46. ,  46.5,  47. ,  47.5,  48. ,  48.5,  49. ,  49.5])

In [46]:
%timeit np.multiply(d,2)

The slowest run took 19.02 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.59 µs per loop


In [47]:
%timeit d * 2

The slowest run took 22.87 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.57 µs per loop


In [52]:
data = np.random.randint(1,100000,size=100000)

In [53]:
%timeit sum(data)

C:\Users\ZekeLabs\Anaconda3\lib\site-packages\ipykernel_launcher.py:257: RuntimeWarning: overflow encountered in long_scalars


10 loops, best of 3: 21.6 ms per loop


In [54]:
%timeit np.sum(data)

The slowest run took 190.59 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 68.4 µs per loop


In [55]:
x = np.array([-2,-1,2,3,4])

In [56]:
np.absolute(x)

array([2, 1, 2, 3, 4])

In [57]:
np.sin(x)

array([-0.90929743, -0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [59]:
np.log10([5,6,7])

array([ 0.69897   ,  0.77815125,  0.84509804])

#### Advenced Features

In [60]:
x = np.arange(5)

In [61]:
y = np.empty(5)

In [62]:
y

array([ 0.,  0.,  0.,  0.,  0.])

In [63]:
np.multiply(x, 10, out=y)

array([  0.,  10.,  20.,  30.,  40.])

In [64]:
y

array([  0.,  10.,  20.,  30.,  40.])

In [65]:
y = np.multiply(x,10)

In [66]:
y

array([ 0, 10, 20, 30, 40])