In [1]:
import numpy as np

In [3]:
L = np.random.random(100)

In [4]:
%timeit sum(L)

10000 loops, best of 3: 24.6 µs per loop


In [5]:
%timeit np.sum(L)

The slowest run took 14.59 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.23 µs per loop


In [6]:
min(L)

0.006092884087239514

In [12]:
%timeit np.min(L)

The slowest run took 11.06 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.32 µs per loop


In [11]:
%timeit L.min()

The slowest run took 11.99 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.76 µs per loop


In [13]:
L

array([ 0.59762232,  0.40157474,  0.42864852,  0.36257017,  0.64196681,
        0.32193427,  0.90848202,  0.72276555,  0.67138131,  0.75598732,
        0.28481867,  0.96736327,  0.24396544,  0.90895896,  0.65683281,
        0.8728343 ,  0.4042383 ,  0.83431212,  0.42378604,  0.3316446 ,
        0.44927819,  0.96443112,  0.12868223,  0.06941841,  0.62867606,
        0.51467174,  0.22752841,  0.21168768,  0.995028  ,  0.78057568,
        0.42436452,  0.99971015,  0.19138767,  0.1821426 ,  0.42348629,
        0.87975825,  0.60241557,  0.91394513,  0.88709218,  0.07643762,
        0.77470008,  0.44503722,  0.12576938,  0.87859488,  0.13302676,
        0.23085521,  0.11201167,  0.21504282,  0.44883861,  0.57170936,
        0.28841328,  0.4319974 ,  0.24481623,  0.1518047 ,  0.31835686,
        0.00609288,  0.30953192,  0.25852794,  0.72015503,  0.62726792,
        0.59076116,  0.80940304,  0.29270523,  0.29274198,  0.10089274,
        0.1981226 ,  0.1652087 ,  0.0122724 ,  0.27511959,  0.35

#### Multi dimensional aggregates

In [2]:
np.random.randint(1,10,size=(3,4))

array([[3, 3, 2, 6],
       [3, 6, 1, 6],
       [1, 9, 7, 9]])

In [3]:
M = np.random.random((3,4))

In [4]:
M

array([[ 0.64837829,  0.10448068,  0.6772774 ,  0.64597081],
       [ 0.58460628,  0.92537614,  0.21451526,  0.61521558],
       [ 0.9737452 ,  0.67431467,  0.71042562,  0.84950284]])

In [16]:
np.sum(M,axis=1)

array([ 2.14835089,  2.41310974,  1.67422818])

In [17]:
np.max(M,axis=1)

array([ 0.87964558,  0.86281712,  0.84743185])

In [18]:
np.max(M,axis=0)

array([ 0.87964558,  0.72428475,  0.86281712,  0.79662629])

In [19]:
K = np.array([3,4,6,7,71])

In [20]:
#Index of max value
np.argmax(K)

4

In [22]:
#Index of min value
np.argmin(K)

0

In [23]:
np.mean(K)

18.199999999999999

In [24]:
np.std(K)

26.437851652507621

In [25]:
np.median(K)

6.0

In [4]:
help(np.median)

Help on function median in module numpy.lib.function_base:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.
    
    Returns the median of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default
        is to compute the median along a flattened version of the array.
        A sequence of axes is supported since version 1.9.0.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
       If True, then allow use of memory of input array `a` for
       calculations. The input array will be modified by the c

In [26]:
D = np.array([1,0,2,3])

In [28]:
#Returns TRue if all elements are non-zero
np.all(D)

False

In [4]:
import numpy as np

In [8]:
a = np.matrix('1 2; 3 4')
type(a)

numpy.matrixlib.defmatrix.matrix

In [3]:
#Returns True if any of the element non-zero


np.any(D)

NameError: name 'D' is not defined

### Comparisons, Masks & Boolean Logic

In [9]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [8]:
import numpy as np
data = np.random.randint(1,10,size=1000)
data[np.where(data == 5)]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
x[x < 5]

array([1, 2, 3, 4])

In [4]:
np.where(x == 5)

(array([4], dtype=int64),)

In [32]:
x[x < 5]

array([1, 2, 3, 4])

In [34]:
#Returns mask array on using comparsion operator
x < 5

array([ True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [38]:
#If logic1 or logic2 is true, have True in Mask array
x[(x < 5) | (x > 8)]

array([1, 2, 3, 4, 9])

In [40]:
x[(x < 5) | (x > 8)]

array([1, 2, 3, 4, 9])

In [8]:
x[ (x%2==0) & (x%3==0)]

array([6])

In [11]:
#1 & 3 are the index of the data which we want to fetch
x[np.array([1,3])]

array([2, 4])

In [5]:
x[np.array([1,2])]

array([2, 3])

In [44]:
bin(8)

'0b1000'

In [45]:
bin(10)

'0b1010'

In [46]:
bin(8 or 10)

'0b1000'

In [47]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
indx = [3,4,8]

In [50]:
x[indx]

array([4, 5, 9])

In [5]:
import numpy as np
M = np.random.randint(1,100,(5,5))

In [6]:
M

array([[17,  6,  4, 42, 95],
       [ 7, 82,  3, 25, 69],
       [26, 63, 63, 47, 19],
       [87, 91,  7, 60, 51],
       [79, 93, 29, 29, 57]])

In [11]:
N = np.array(['a','b','c','d','e'])
N[np.random.randint(0,5,size=100)]

array(['a', 'e', 'd', 'a', 'c', 'e', 'e', 'a', 'e', 'c', 'd', 'c', 'a',
       'e', 'a', 'b', 'e', 'd', 'a', 'c', 'd', 'b', 'd', 'e', 'e', 'a',
       'c', 'd', 'd', 'c', 'a', 'e', 'd', 'b', 'c', 'd', 'c', 'c', 'e',
       'd', 'e', 'c', 'c', 'e', 'a', 'e', 'e', 'a', 'e', 'a', 'c', 'e',
       'd', 'c', 'a', 'c', 'c', 'c', 'c', 'e', 'c', 'e', 'd', 'c', 'b',
       'a', 'a', 'b', 'd', 'a', 'e', 'a', 'e', 'b', 'c', 'b', 'a', 'c',
       'a', 'a', 'a', 'e', 'a', 'e', 'e', 'b', 'a', 'c', 'c', 'a', 'd',
       'd', 'c', 'c', 'a', 'd', 'b', 'e', 'c', 'a'],
      dtype='<U1')

In [57]:
indx = np.array([1,3])
indx

array([1, 3])

In [58]:
data = M[indx]
data

array([[41, 12, 29, 63, 60],
       [95, 12, 49,  8, 25]])

In [54]:
indx = np.array([ [1],[3] ])
indx

array([[1],
       [3]])

In [55]:
M[indx]

array([[[41, 12, 29, 63, 60]],

       [[95, 12, 49,  8, 25]]])

In [40]:
M[1]

array([41, 12, 29, 63, 60])

In [14]:
M[np.arange(1,5,2)]
#Generate indices programmatically

array([[45, 89, 59, 41, 67],
       [33, 23, 41, 63,  8]])

In [11]:
# Create a 
d = np.arange(10)
d[:,np.newaxis,np.newaxis].shape

(10, 1, 1)

In [10]:
# Adds one more dimension
d[:, np.newaxis, np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [9]:
d.reshape((10,1,1))

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [47]:
X = np.arange(12).reshape((3,4))

In [50]:
X.shape

(3, 4)

In [51]:
#np.newaxis will add one more dimension
X[:,np.newaxis].shape

(3, 1, 4)

In [52]:
X[:,np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [14]:
x = np.array([1,2,3,4])

In [19]:
x[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [84]:
X[:,np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [9]:
X.transpose()
#Converts rows to column & column to rows

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
X.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [89]:
l = (1,)

In [90]:
type(l)

tuple

In [91]:
l = (1)

In [92]:
type(l)

int

#### sort and argsort

In [95]:
np.sort(np.array([2,1,1,1,3]))

array([1, 1, 1, 2, 3])

In [96]:
np.argsort(np.array([2,1,1,1,3]))
#Returns index of sorted data

array([1, 2, 3, 0, 4], dtype=int64)

In [98]:
M

array([[97, 27, 61, 83, 57],
       [27, 65, 10, 26, 96],
       [38, 33, 19, 58, 71],
       [92, 63, 96, 76, 16],
       [81, 76,  9, 92, 70]])

In [99]:
#axis 1 - sorting row wise
np.sort(M,axis=1)

array([[27, 57, 61, 83, 97],
       [10, 26, 27, 65, 96],
       [19, 33, 38, 58, 71],
       [16, 63, 76, 92, 96],
       [ 9, 70, 76, 81, 92]])

In [101]:
#axis 0 - sorting col wise
np.sort(M,axis=0)

array([[27, 27,  9, 26, 16],
       [38, 33, 10, 58, 57],
       [81, 63, 19, 76, 70],
       [92, 65, 61, 83, 71],
       [97, 76, 96, 92, 96]])

In [1]:
import numpy as np

In [13]:
d = np.random.randint(1,100,(5,5))

In [14]:
d

array([[18, 13, 45, 58, 52],
       [62,  5, 94,  1, 91],
       [11, 15, 38, 54, 49],
       [56, 85,  7, 40, 42],
       [89, 56, 40, 58,  1]])

In [15]:
d[:,1:4]

array([[13, 45, 58],
       [ 5, 94,  1],
       [15, 38, 54],
       [85,  7, 40],
       [56, 40, 58]])

In [17]:
d[1:3, 1:3]

array([[ 5, 94],
       [15, 38]])

In [18]:
d[3:,3:]

array([[40, 42],
       [58,  1]])

In [13]:
import numpy as np

In [14]:
a = np.array([ [1,2,3], [4,5,6]])

In [15]:
b = np.array( [ [2], [1]])

In [16]:
a.shape

(2, 3)

In [17]:
b.shape

(2, 1)

In [18]:
a * b

array([[2, 4, 6],
       [4, 5, 6]])

In [22]:
np.multiply(a,b)

array([[2, 4, 6],
       [4, 5, 6]])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a = np.array([ [1,2,3], [4,5,6], [7,8,9]])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
c = np.array([[5,6,7]])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
c.shape

(1, 3)

In [30]:
a * c

array([[ 5, 12, 21],
       [20, 30, 42],
       [35, 48, 63]])