In [3]:
import numpy as np

In [3]:
#Genrating data from 0 - 9
data = np.arange(10)

In [4]:
data.shape

(10,)

In [5]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
new_data = data.reshape((10,1))

In [6]:
new_data

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
# l = [[1,2,3], [4,5,6], [7,8,9]]
# l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
new_data.shape

(10, 1)

In [9]:
data.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
data.reshape((2,5)).shape

(2, 5)

In [11]:
data.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array Concatenation & Splitting

In [32]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y,x])
#concat of 1-D data creates 1 D storage
#Since, 1D data, no concept of axis

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [35]:
xx = np.array([ [1,2,3], [4,5,6], [7,8,9]])
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
#on concat, sits on top of another
np.concatenate([xx,xx])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# axis 1 - horizontal
# axis 0 - vertical
np.concatenate([xx,xx],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [18]:
x

array([1, 2, 3])

In [19]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#Stacking vertically
# Num. of columns should be same
np.vstack([x,xx])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#Stacking horizontally
#Num of rows should be same
np.hstack([xx,xx])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

#### Splitting arrays

In [1]:
x = [0,1,2,3,4,5,6,67,7]

In [4]:
#Splitting based on index 3 & 5
np.split(x,[3,5])

[array([0, 1, 2]), array([3, 4]), array([ 5,  6, 67,  7])]

In [28]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#Splits the vertical axis
#we have to split vertical axis & this is done horizontally
np.vsplit(xx,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [33]:
a,b = np.hsplit(xx,[1])

In [34]:
a

array([[1],
       [4],
       [7]])

In [35]:
b

array([[2, 3],
       [5, 6],
       [8, 9]])

#### Computation on NumPy Arrays

In [36]:
d = np.arange(100)

In [37]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
d + 5

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104])

In [43]:
np.concatenate([d[:50] * 2, d[50:]])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
d[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
d / 2

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,
        13.5,  14. ,  14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,
        18. ,  18.5,  19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,
        22.5,  23. ,  23.5,  24. ,  24.5,  25. ,  25.5,  26. ,  26.5,
        27. ,  27.5,  28. ,  28.5,  29. ,  29.5,  30. ,  30.5,  31. ,
        31.5,  32. ,  32.5,  33. ,  33.5,  34. ,  34.5,  35. ,  35.5,
        36. ,  36.5,  37. ,  37.5,  38. ,  38.5,  39. ,  39.5,  40. ,
        40.5,  41. ,  41.5,  42. ,  42.5,  43. ,  43.5,  44. ,  44.5,
        45. ,  45.5,  46. ,  46.5,  47. ,  47.5,  48. ,  48.5,  49. ,  49.5])

### Performance Measurement

In [8]:
def f():
    l = []
    for i in range(10000000):
        l.append(i)
        l[i] = l[i] * 2
        
%timeit f

10000000 loops, best of 3: 39.9 ns per loop


In [7]:
n = np.arange(100000)
%timeit np.multiply(n,2)

1000 loops, best of 3: 177 µs per loop


In [ ]:
data = np.random.randint(1,1000000,size=(100000,10000))

In [46]:
%timeit np.multiply(d,2)

The slowest run took 19.02 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.59 µs per loop


In [47]:
%timeit d * 2

The slowest run took 22.87 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.57 µs per loop


In [28]:
#Genrates size of random numbers between 1 & 100000
data = np.random.randint(1,100000,size=100000)

In [30]:
#max is generic python function not a numpy function
%timeit max(data)

100 loops, best of 3: 11.5 ms per loop


In [31]:
#np.max is a numpy library
%timeit np.max(data)

10000 loops, best of 3: 153 µs per loop


In [53]:
%timeit sum(data)

C:\Users\ZekeLabs\Anaconda3\lib\site-packages\ipykernel_launcher.py:257: RuntimeWarning: overflow encountered in long_scalars


10 loops, best of 3: 21.6 ms per loop


In [54]:
%timeit np.sum(data)

The slowest run took 190.59 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 68.4 µs per loop


In [55]:
x = np.array([-2,-1,2,3,4])

In [56]:
np.absolute(x)

array([2, 1, 2, 3, 4])

In [57]:
np.sin(x)

array([-0.90929743, -0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [59]:
np.log10([5,6,7])

array([ 0.69897   ,  0.77815125,  0.84509804])

#### Advenced Features

In [10]:
x = np.arange(5)

In [13]:
#creating 5 placeholders in y
y = np.empty(5)

In [14]:
y

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
#using 5 data of pre-allocated y
np.multiply(x, 10, out=y)

array([  0.,  10.,  20.,  30.,  40.])

In [64]:
y

array([  0.,  10.,  20.,  30.,  40.])

In [65]:
y = np.multiply(x,10)

In [66]:
y

array([ 0, 10, 20, 30, 40])

In [11]:
x

array([0, 1, 2, 3, 4])

In [17]:
import numpy as np

In [18]:
help(np.argpartition)

Help on function argpartition in module numpy.core.fromnumeric:

argpartition(a, kth, axis=-1, kind='introselect', order=None)
    Perform an indirect partition along the given axis using the
    algorithm specified by the `kind` keyword. It returns an array of
    indices of the same shape as `a` that index data along the given
    axis in partitioned order.
    
    .. versionadded:: 1.8.0
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    kth : int or sequence of ints
        Element index to partition by. The k-th element will be in its
        final sorted position and all smaller elements will be moved
        before it and all larger elements behind it. The order all
        elements in the partitions is undefined. If provided with a
        sequence of k-th it will partition all of them into their sorted
        position at once.
    axis : int or None, optional
        Axis along which to sort. The default is -1 (the last axis). If
        None, t

In [19]:
x = np.array([3, 4, 2, 1])

In [22]:
np.argpartition(x,1)

array([3, 2, 1, 0], dtype=int64)

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [24]:
a * b

array([ 4, 10, 18])

In [26]:
y = np.empty(3)
np.multiply(a,b, out=y)

array([  4.,  10.,  18.])

In [27]:
y

array([  4.,  10.,  18.])

In [28]:
np.dot(a,b)

32

In [ ]:
np.matmul