In [4]:
import numpy as np

In [2]:
#Genrating data from 0 - 9
data = np.arange(10)

In [5]:
#shape of data
data.shape

(10,)

In [6]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#num of dim of data
data.ndim

1

In [8]:
data.size

10

In [9]:
new_data = data.reshape((10,1))

In [10]:
new_data

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
new_data.ndim

2

In [12]:
# l = [[1,2,3], [4,5,6], [7,8,9]]
# l

In [13]:
new_data.shape

(10, 1)

In [14]:
data.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
data.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
data.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array Concatenation & Splitting

In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y,x])
#concat of 1-D data creates 1 D storage
#Since, 1D data, no concept of axis

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [4]:
xx = np.array([ [1,2,3], [4,5,6], [7,8,9]])
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#on concat, sits on top of another
np.concatenate([xx,xx[:2]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
help(np.concatenate)

Help on built-in function concatenate in module numpy.core.multiarray:

concatenate(...)
    concatenate((a1, a2, ...), axis=0)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  Default is 0.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
                  near-equal size.
    split : Split array into a list of multiple sub-arrays of equal size.
    hsplit : Split array into multiple sub-arrays horizontally (column wise)
    vsplit : Split array into multiple sub-arrays vertically (row wise)
    dsp

In [24]:
# axis 1 - horizontal
# axis 0 - vertical
np.concatenate([xx,xx],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [18]:
x

array([1, 2, 3])

In [19]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#Stacking vertically
# Num. of columns should be same
np.vstack([x,xx])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#Stacking horizontally
#Num of rows should be same
np.hstack([xx,xx])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

#### Splitting arrays

In [6]:
x = [0,1,2,3,4,5,6,67,7]

In [12]:
#Splitting based on index 3 & 5
np.split(x,[3,5,6])

[array([0, 1, 2]), array([3, 4]), array([5]), array([ 6, 67,  7])]

In [28]:
xx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#Splits the vertical axis
#we have to split vertical axis & this is done horizontally
np.vsplit(xx,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [33]:
a,b = np.hsplit(xx,[1])

In [34]:
a

array([[1],
       [4],
       [7]])

In [35]:
b

array([[2, 3],
       [5, 6],
       [8, 9]])

#### Computation on NumPy Arrays

In [8]:
d = np.arange(100)

In [15]:
#np.matmul

In [9]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
#slicing
d[4:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
d + 5

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104])

In [10]:
np.concatenate([d[:50] * 2, d[50:]])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.concatenate([d[:25]*2, d[25:50]*4,d[50:75]*8,d[75:]*16]).reshape(4,25)

array([[   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
          22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
          44,   46,   48],
       [ 100,  104,  108,  112,  116,  120,  124,  128,  132,  136,  140,
         144,  148,  152,  156,  160,  164,  168,  172,  176,  180,  184,
         188,  192,  196],
       [ 400,  408,  416,  424,  432,  440,  448,  456,  464,  472,  480,
         488,  496,  504,  512,  520,  528,  536,  544,  552,  560,  568,
         576,  584,  592],
       [1200, 1216, 1232, 1248, 1264, 1280, 1296, 1312, 1328, 1344, 1360,
        1376, 1392, 1408, 1424, 1440, 1456, 1472, 1488, 1504, 1520, 1536,
        1552, 1568, 1584]])

In [44]:
d / 2

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,
        13.5,  14. ,  14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,
        18. ,  18.5,  19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,
        22.5,  23. ,  23.5,  24. ,  24.5,  25. ,  25.5,  26. ,  26.5,
        27. ,  27.5,  28. ,  28.5,  29. ,  29.5,  30. ,  30.5,  31. ,
        31.5,  32. ,  32.5,  33. ,  33.5,  34. ,  34.5,  35. ,  35.5,
        36. ,  36.5,  37. ,  37.5,  38. ,  38.5,  39. ,  39.5,  40. ,
        40.5,  41. ,  41.5,  42. ,  42.5,  43. ,  43.5,  44. ,  44.5,
        45. ,  45.5,  46. ,  46.5,  47. ,  47.5,  48. ,  48.5,  49. ,  49.5])

In [20]:
d = np.arange(2,99,2).reshape(7,7)
d

array([[ 2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80, 82, 84],
       [86, 88, 90, 92, 94, 96, 98]])

In [24]:
d = np.append(d,np.NaN)
np.append(d,np.NaN)

d.shape

(51,)

In [46]:
r,c = np.shape(d)
d[int(np.floor(r/2)),int(np.floor(c/2))]

50

In [28]:
d = np.round(3.1269,3)
d

3.1269999999999998

### Performance Measurement

In [30]:
def f():
    l = []
    for i in range(10000000):
        l.append(i)
        l[i] = l[i] * 2
        
%timeit f()

5.05 s ± 305 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
n = np.arange(10000000)
%timeit np.multiply(n,2)

70.6 ms ± 1.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
data = np.random.randint(1,1000000,size=(100000,10000))

In [22]:
n = list(range(100000))
def f():
    l = []
    for i in n:
        l.append(2*i)
%timeit f()

10 loops, best of 3: 31.8 ms per loop


In [23]:
%timeit np.multiply(d,2)

The slowest run took 18.83 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.42 µs per loop


In [24]:
%timeit d * 2

The slowest run took 25.96 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.7 µs per loop


In [25]:
#Genrates size of random numbers between 1 & 100000
data = np.random.randint(1,100000,size=100000)

In [28]:
#max is generic python function not a numpy function
%timeit max(data)

100 loops, best of 3: 13.5 ms per loop


In [32]:
l = [[1,12],[3,4]]
max(l,key=lambda x:x[1])

[1, 12]

In [29]:
#np.max is a numpy library
%timeit np.max(data)

1000 loops, best of 3: 180 µs per loop


In [53]:
%timeit sum(data)

C:\Users\ZekeLabs\Anaconda3\lib\site-packages\ipykernel_launcher.py:257: RuntimeWarning: overflow encountered in long_scalars


10 loops, best of 3: 21.6 ms per loop


In [54]:
%timeit np.sum(data)

The slowest run took 190.59 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 68.4 µs per loop


In [55]:
x = np.array([-2,-1,2,3,4])

In [56]:
np.absolute(x)

array([2, 1, 2, 3, 4])

In [57]:
np.sin(x)

array([-0.90929743, -0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [59]:
np.log10([5,6,7])

array([ 0.69897   ,  0.77815125,  0.84509804])

#### Advenced Features

In [10]:
x = np.arange(5)

In [13]:
#creating 5 placeholders in y
y = np.empty(5)

In [14]:
y

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
#using 5 data of pre-allocated y
np.multiply(x, 10, out=y)

array([  0.,  10.,  20.,  30.,  40.])

In [64]:
y

array([  0.,  10.,  20.,  30.,  40.])

In [65]:
y = np.multiply(x,10)

In [66]:
y

array([ 0, 10, 20, 30, 40])

In [11]:
x

array([0, 1, 2, 3, 4])

In [17]:
import numpy as np

In [18]:
help(np.argpartition)

Help on function argpartition in module numpy.core.fromnumeric:

argpartition(a, kth, axis=-1, kind='introselect', order=None)
    Perform an indirect partition along the given axis using the
    algorithm specified by the `kind` keyword. It returns an array of
    indices of the same shape as `a` that index data along the given
    axis in partitioned order.
    
    .. versionadded:: 1.8.0
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    kth : int or sequence of ints
        Element index to partition by. The k-th element will be in its
        final sorted position and all smaller elements will be moved
        before it and all larger elements behind it. The order all
        elements in the partitions is undefined. If provided with a
        sequence of k-th it will partition all of them into their sorted
        position at once.
    axis : int or None, optional
        Axis along which to sort. The default is -1 (the last axis). If
        None, t

In [19]:
x = np.array([3, 4, 2, 1])

In [22]:
np.argpartition(x,1)

array([3, 2, 1, 0], dtype=int64)

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [8]:
print(a * b)
np.dot(a,b)

[ 4 10 18]


32

In [9]:
a * 3

array([3, 6, 9])

In [10]:
np.multiply(a,3)

array([3, 6, 9])

In [26]:
y = np.empty(3)
np.multiply(a,b, out=y)

array([  4.,  10.,  18.])

In [27]:
y

array([  4.,  10.,  18.])

In [28]:
np.dot(a,b)

32

In [ ]:
np.matmul

In [11]:
import numpy as np

In [13]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
a * b

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [18]:
#np.matmul(a,b)

In [7]:
b

array([[0],
       [1],
       [2],
       [3]])

In [12]:
c = np.arange(9).reshape(3,3)

In [13]:
np.matmul(a,c)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111],
       [ 96, 126, 156]])

In [14]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
a.shape

(4, 3)

In [17]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
b = np.arange(6).reshape(2,3)

In [23]:
a * b

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

In [20]:
a.shape

(4, 3)

In [21]:
b.shape

(1, 3)

In [37]:
a = np.arange(12).reshape((6,2))

In [38]:
b = np.arange(2,4)

In [39]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [40]:
b

array([2, 3])

In [42]:
an = a.reshape(6,1,2)

In [43]:
bn = b.reshape(2,1)

In [44]:
bn

array([[2],
       [3]])

In [46]:
np.subtract(an,bn)

array([[[-2, -1],
        [-3, -2]],

       [[ 0,  1],
        [-1,  0]],

       [[ 2,  3],
        [ 1,  2]],

       [[ 4,  5],
        [ 3,  4]],

       [[ 6,  7],
        [ 5,  6]],

       [[ 8,  9],
        [ 7,  8]]])

In [30]:
d.shape

(2, 2, 3)

In [48]:
c = np.zeros((3,3))

In [52]:
o = np.ones((1,3))

In [50]:
c

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [53]:
o

array([[ 1.,  1.,  1.]])

In [58]:
r = np.vstack([o,c,o])

In [57]:
v = np.ones((5,1))

In [59]:
np.hstack([v,r,v])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])