### NumPy ( Numerical Python )
* Storage for ndim data
* Have lot of methods to make ndim data processing easier
* Very fast - C like storage
* Homogenous data storage

In [2]:
import numpy as np

In [5]:
l = [1,2,3,4,5]
# Creating Arrays from Python List - converting list into python np.array
np_data = np.array([1,2,3,4,5])

In [4]:
type(np_data)

numpy.ndarray

In [6]:
np_data

array([1, 2, 3, 4, 5])

In [9]:
#Creating from scratch
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((5,5,5))
#sizes of more than 1d will be passed in tuple

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [15]:
np.full((5,5),66)

array([[66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66]])

In [42]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [18]:
np.linspace(5,10,20)
#Between 5 to 10, it generated 20 equal spaced numbers

array([  5.        ,   5.26315789,   5.52631579,   5.78947368,
         6.05263158,   6.31578947,   6.57894737,   6.84210526,
         7.10526316,   7.36842105,   7.63157895,   7.89473684,
         8.15789474,   8.42105263,   8.68421053,   8.94736842,
         9.21052632,   9.47368421,   9.73684211,  10.        ])

In [19]:
np.random.random((4,4))

array([[ 0.75836224,  0.77547423,  0.96067163,  0.27300614],
       [ 0.06256564,  0.03145407,  0.39631174,  0.34845902],
       [ 0.8562364 ,  0.41329573,  0.16504176,  0.32637266],
       [ 0.38734393,  0.48944434,  0.51530952,  0.66307372]])

In [20]:
np.random.randint(0,10,size=(3,3))

array([[0, 3, 6],
       [4, 8, 1],
       [6, 7, 1]])

### Accessing Elements

In [21]:
data = np.random.randint(0,10,size=5)

In [24]:
data

array([3, 3, 1, 4, 9])

In [25]:
data[0]

3

In [26]:
data[-1]

9

In [27]:
data[2:5]

array([1, 4, 9])

In [34]:
ndata = np.random.randint(0,10,size=(4,5))

In [35]:
ndata[1,1]

5

In [36]:
ndata

array([[1, 5, 3, 6, 0],
       [4, 5, 2, 2, 3],
       [3, 8, 0, 0, 5],
       [3, 2, 7, 3, 6]])

In [32]:
ndata[1,1] = 9999

In [33]:
ndata

array([[   0,    1,    0,    1,    7],
       [   8, 9999,    2,    3,    0],
       [   6,    0,    2,    0,    9],
       [   2,    6,    0,    8,    9]])

In [37]:
#### Genrating same seq of random numbers



In [39]:
np.random.seed(10)
np.random.randint(10,size=5)

array([9, 4, 0, 1, 9])

In [40]:
np.random.seed(10)
np.random.randint(10,size=5)

array([9, 4, 0, 1, 9])

In [43]:
ndata

array([[1, 5, 3, 6, 0],
       [4, 5, 2, 2, 3],
       [3, 8, 0, 0, 5],
       [3, 2, 7, 3, 6]])

In [44]:
ndata[:2]

array([[1, 5, 3, 6, 0],
       [4, 5, 2, 2, 3]])

In [46]:
ndata[2:4,:2]

array([[3, 8],
       [3, 2]])

In [48]:
ndata[1:3,2:4]

array([[2, 2],
       [0, 0]])

In [50]:
ndata[-3:-2]

array([[4, 5, 2, 2, 3]])

In [51]:
ndata

array([[1, 5, 3, 6, 0],
       [4, 5, 2, 2, 3],
       [3, 8, 0, 0, 5],
       [3, 2, 7, 3, 6]])

### Reshaping of Arrays

In [52]:
data = np.arange(0,10)

In [54]:
data.shape

(10,)

In [55]:
data.size

10

In [56]:
data.ndim

1

In [57]:
ndata = data.reshape((2,5))

In [58]:
ndata.shape

(2, 5)

In [59]:
ndata.ndim

2

In [60]:
ndata.size

10

In [61]:
ndata

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
print('hello')

hello
