In [1]:
import numpy as np

In [2]:
x = np.arange(4)

In [3]:
xx = x.reshape(4,1)

In [4]:
x

array([0, 1, 2, 3])

In [5]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [6]:
xx.shape

(4, 1)

In [7]:
y = np.ones(5)

In [10]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [9]:
xx + y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

Thumb Rule
4 X 1, 
    5 
------
4 X 5

In [19]:
x

array([0, 1, 2, 3])

In [14]:
z = np.ones((3,4))

In [17]:
z.shape

(3, 4)

In [ ]:
3 X 4
    4
-----
3 X 4

In [23]:
x - z

array([[-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.]])

In [20]:
z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5

Cannot be done
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched

In [26]:
a = np.array([1,2,3,5])
b = np.array([1,2,3,4])

In [27]:
a - b

array([0, 0, 0, 1])

In [28]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])

In [29]:
a

array([[  0.,   0.,   0.],
       [ 10.,  10.,  10.],
       [ 20.,  20.,  20.],
       [ 30.,  30.,  30.]])

In [30]:
b = np.array([1.0,2.0,3.0]) 

In [31]:
a.shape

(4, 3)

In [32]:
b.shape

(3,)

In [33]:
a + b

array([[  1.,   2.,   3.],
       [ 11.,  12.,  13.],
       [ 21.,  22.,  23.],
       [ 31.,  32.,  33.]])

### Rules
* Arrays should be of same size
* Arrays have the same number of dimensions & length of each dim is common or 1
* Arrays having lesser dim can have shape replaced with 1 so that it becomes the above case

In [34]:
a = np.arange(12).reshape((6,2))
b = np.arange(4).reshape((2,2))

In [35]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
b

array([[0, 1],
       [2, 3]])

In [37]:
an = a.reshape((6,1,2))

In [38]:
an

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]]])

In [39]:
an + b

array([[[ 0,  2],
        [ 2,  4]],

       [[ 2,  4],
        [ 4,  6]],

       [[ 4,  6],
        [ 6,  8]],

       [[ 6,  8],
        [ 8, 10]],

       [[ 8, 10],
        [10, 12]],

       [[10, 12],
        [12, 14]]])

In [43]:
a = np.arange(12).reshape((4,3))
b = np.arange(6).reshape((3,2))

In [46]:
an = a.reshape((4,3,1))
bn = b.reshape  ((3,2))

In [47]:
an + bn

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[ 3,  4],
        [ 6,  7],
        [ 9, 10]],

       [[ 6,  7],
        [ 9, 10],
        [12, 13]],

       [[ 9, 10],
        [12, 13],
        [15, 16]]])

In [48]:
an

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]]])

In [49]:
a = np.arange(4)
b = np.arange(3)

In [50]:
a.reshape(4,1) + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])