### Predicting petal_width using sepal length - Pipeline concept

In [1]:
import seaborn as sns
iris = sns.load_dataset('iris')

In [3]:
X = iris['sepal_length']
Y = iris['petal_width']

In [8]:
X = X.values.reshape(X.values.shape[0],1)
#X.values[:,np.newaxis]

In [26]:
X

array([[ 5.1],
       [ 4.9],
       [ 4.7],
       [ 4.6],
       [ 5. ],
       [ 5.4],
       [ 4.6],
       [ 5. ],
       [ 4.4],
       [ 4.9],
       [ 5.4],
       [ 4.8],
       [ 4.8],
       [ 4.3],
       [ 5.8],
       [ 5.7],
       [ 5.4],
       [ 5.1],
       [ 5.7],
       [ 5.1],
       [ 5.4],
       [ 5.1],
       [ 4.6],
       [ 5.1],
       [ 4.8],
       [ 5. ],
       [ 5. ],
       [ 5.2],
       [ 5.2],
       [ 4.7],
       [ 4.8],
       [ 5.4],
       [ 5.2],
       [ 5.5],
       [ 4.9],
       [ 5. ],
       [ 5.5],
       [ 4.9],
       [ 4.4],
       [ 5.1],
       [ 5. ],
       [ 4.5],
       [ 4.4],
       [ 5. ],
       [ 5.1],
       [ 4.8],
       [ 5.1],
       [ 4.6],
       [ 5.3],
       [ 5. ],
       [ 7. ],
       [ 6.4],
       [ 6.9],
       [ 5.5],
       [ 6.5],
       [ 5.7],
       [ 6.3],
       [ 4.9],
       [ 6.6],
       [ 5.2],
       [ 5. ],
       [ 5.9],
       [ 6. ],
       [ 6.1],
       [ 5.6],
       [ 6.7],
       [ 5

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [20]:
def create_pipeline(degrees):
    pipeline = make_pipeline(PolynomialFeatures(degrees),LinearRegression(fit_intercept=True))
    return pipeline
    

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [34]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y)

In [45]:
models = []
for degree in range(2,35):
    #this will create a pipeline with mentioned degree & estimator as linear regression
    pipeline = create_pipeline(degree)
    pipeline.fit(Xtrain,Ytrain)
    pred = pipeline.predict(Xtest)
    print (r2_score(Ytest,pred))
    models.append([degree,r2_score(Ytest,pred),pipeline])
    

0.621979412019
0.676323877222
0.668042115698
0.673909392348
0.682237655709
0.675521975762
0.668068970156
0.669402503074
0.67430133089
0.676747459766
0.676987466396
0.676051383454
0.674718279447
0.673514873088
0.672765921405
0.672566855253
0.672834187715
0.673352862581
0.673850216485
0.67411348102
0.674006774946
0.673531350525
0.668497036835
0.669505431318
0.670648044736
0.671710359982
0.672441024015
0.67275955555
0.672663116227
0.672262948112
0.671704250353
0.671208357369
0.670780674418


In [25]:
create_pipeline(2)

Pipeline(memory=None,
     steps=[('polynomialfeatures', PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)), ('linearregression', LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False))])

In [17]:
Xtrain.shape

(112, 1)

In [18]:
Ytrain.shape

(38, 1)

In [47]:
top_models = sorted(models,key = lambda d: d[1],reverse=True)[:5]

In [52]:
top_models[0][2].predict([[6.2],[5.9]])

array([ 1.781523  ,  1.47476482])

In [54]:
Y[-2:]

148    2.3
149    1.8
Name: petal_width, dtype: float64

In [56]:
top_models[3][2].predict([[6.2],[5.9]])

array([ 1.63913345,  1.36675312])

### 