### Simple Linear Regression
* It models the relationship between one response variable & one feature of an explanatory variable

In [1]:
import numpy as np

In [2]:
X = np.linspace(1,100,1000)

In [3]:
Y = 5*X + 50

In [6]:
#We are trying to get the best line which can predict Y for a given X

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
model = LinearRegression()

In [13]:
model.fit(X.reshape(-1,1),Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
model.coef_

array([ 5.])

In [15]:
model.intercept_

50.000000000000199

In [16]:
model.predict([[4]])

array([ 70.])

In [17]:
### Polynomial Curve

In [20]:
Y_pol = 5*X**2 + 7*X + 10

In [23]:
from sklearn.preprocessing import PolynomialFeatures

In [26]:
poly = PolynomialFeatures(2)

In [27]:
poly.fit_transform([[2],[3]])

array([[ 1.,  2.,  4.],
       [ 1.,  3.,  9.]])

In [28]:
X_data = poly.fit_transform(X[:,np.newaxis])

In [30]:
X_data[2]

array([ 1.        ,  1.1981982 ,  1.43567892])

In [31]:
model.fit(X_data,Y_pol)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
model.coef_

array([ 0.,  7.,  5.])

In [33]:
model.intercept_

10.0